### ISSUE TITLE
大佬们，目前int4版本支持微调吗？

### ISSUE THREAD

**Issue by dingle0422** [ssbuild/chatglm_finetuning#102]
我把”load_pretrain_weight_int4“设置为True，就报错；但是设置为False，却也可以进行对6b_in4进行训练。
所以设不设定这个参数是无所谓的吗？

**Comment by ssbuild** [comment]
1. 目前只支持加载 int4冻结模型推理 ， 不支持训练
2. 如果需要加载推理量化后模型，请开启选项， 如果是动态量化模型或者加载不是int模型关掉该选项。

**Comment by dingle0422** [comment]
> 

谢谢大佬，所以我刚刚按我设为False的方法，并且训练了结果loss一直都不变，就是因为不支持训练导致的吗？

**Comment by dingle0422** [comment]
> 1. 目前只支持加载 int4冻结模型推理 ， 不支持训练
> 2. 如果需要加载量化后模型推理，请开启选项， 如果是动态量化模型或者加载不是int模型关掉该选项。
![image](https://user-images.githubusercontent.com/68275662/228788617-7b5163e1-4733-46b5-8cfb-8ac79dc1058e.png)

**Comment by dingle0422** [comment]
所以现在FP16和INT8支持训练吗？大佬
![image](https://user-images.githubusercontent.com/68275662/228789164-2fe78312-9afc-415c-95b8-b5a08c072263.png)

**Comment by weizhenzhao** [comment]
同问，int4类型的权重，应该怎样才能支持训练呀？
