### ISSUE TITLE
请问lora模式怎么冻结预训练模型的权重？

### ISSUE THREAD

**Issue by liujiefei** [ssbuild/chatglm_finetuning#103]

**Comment by ssbuild** [comment]
lora模式已冻结，不需要认为再冻结, try,

**Comment by liujiefei** [comment]
> lora模式已冻结，不需要人为再冻结, try,
![image](https://user-images.githubusercontent.com/34298673/228801780-53fcb777-0129-4bb2-9a8b-e7204f086d7b.png)

请问lora已经冻结了模型权重，为什么显示模型训练了万分之五的的参数？
