### ISSUE TITLE
一开始就loss=nan，你们都能跑成功？？？？？？

### ISSUE THREAD

**Issue by gg22mm** [ssbuild/chatglm_finetuning#107]
一开始就loss=nan，你们都能跑成功？ 这个应该不用配置什么吧？数据用的是：data\finetune_train_examples.json

![图片](https://user-images.githubusercontent.com/6648329/229038180-c9b6851c-64cd-43ca-8891-617c4740fba7.png)

我看了有些说是：
1、train.py 添加参数 precision=16 。 没有解决，直接报错
2、'learning_rate': 2e-6,  #2e-5  也不成功
然后搜索了一翻，也没有个能解决的。

环境：
![图片](https://user-images.githubusercontent.com/6648329/229040345-b000461a-444b-47d1-8b99-588fc8baaa8a.png)

![图片](https://user-images.githubusercontent.com/6648329/229040495-89831906-a461-4f61-8170-752f38b1a23f.png)

**Comment by ssbuild** [comment]
建议加载官方权重，使用全参数训练 ！

**Comment by gg22mm** [comment]
> 官方权重

您好，我就是加载的官方权重的如：
![图片](https://user-images.githubusercontent.com/6648329/229040950-0149f1fb-8d30-4297-a59d-8b41f500d261.png)
![图片](https://user-images.githubusercontent.com/6648329/229041092-b8b322d4-9b91-40ed-87a7-231c27eb272f.png)

**Comment by gg22mm** [comment]
？？  怎么回事，关闭了？ 没解决呢

**Comment by ssbuild** [comment]
重复 #30
