### ISSUE TITLE
没有什么问题 

### ISSUE THREAD

**Issue by archwolf118** [ssbuild/chatglm_finetuning#11]
是我的问题，close this issue

**Comment by JieYueCoding** [comment]
我在运行时会提示这两个依赖不存在
```
from pytorch_lightning  import Trainer
from pytorch_lightning.strategies import DeepSpeedStrategy
```
当我 `pip install pytorch-lightning` 后 运行 `python data_utils.py` 提示:`ImportError: cannot import name 'seed_everything' from 'pytorch_lightning.utilities.seed' (xxx\site-packages\pytorch_lightning\utilities\seed.py)
 `
请问有人知道怎么解决吗.

**Comment by archwolf118** [comment]
@JieYueCoding 你装pytorch-lightning==1.9.4试试

**Comment by JieYueCoding** [comment]
@archwolf118 可以了谢谢，
之后有这样的错
```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/nlp/pre_models/torch/chatglm/chatglm-6b'. Use `repo_type` argument if needed.
```
请问是否是需要将 `chatglm-6b` 的八个文件下载下来放在 `/data/nlp/pre_models/torch/chatglm/chatglm-6b` 这个路径下的意思

**Comment by archwolf118** [comment]
@JieYueCoding 必须修改成本地已下载好的chatglm-6b路径
