### ISSUE TITLE
能否在cpu上微调测试？

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [ssbuild/chatglm_finetuning#110]
没有GPU，想先在CPU上进行小样本的微调测试，改成CPU模式需要做哪些修改？

**Comment by ssbuild** [comment]
搞不了 ，建议玩玩 小模型 例如 chatyuan.

**Comment by xiaoyaolangzhi** [comment]
没有多少数据，只是想用几条数据测试下整个流程，计算的慢没关系，没问题了再考虑找gpu来微调，应该可以的吧？
