### ISSUE TITLE
infer_lora_finetuning时也出现weight not used提示，影响结果吗？

### ISSUE THREAD

**Issue by dingle0422** [ssbuild/chatglm_finetuning#114]
@ssbuild 
大佬，我在训练完跑infer_lora_finetuning时也出现了训练时出现的提示：Some weights of the model checkpoint at <my checkpoint path> were not used when initializing MyChatGLMForConditionalGeneration

并且在infer跑完后都没有输出答案，是因为上述的提示影响的吗？如果是，infer时该去哪里开启使用所有预训练模型参数和lora参数呢？

**Comment by ssbuild** [comment]
readme 训练节 ， 全层

**Comment by dingle0422** [comment]
> readme 训练节 ， 全层

已解决 感谢
