### ISSUE TITLE
deepspeed 会卡住

### ISSUE THREAD

**Issue by weizhenzhao** [ssbuild/chatglm_finetuning#116]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/13706689/229259095-7841e8c5-5057-45e0-92c0-b84767ee726c.png">
<img width="995" alt="image" src="https://user-images.githubusercontent.com/13706689/229259162-7f2d50df-6978-4b1a-9724-01d40d405a3f.png">
`
{
  "zero_allow_untested_optimizer": true,
  "zero_force_ds_cpu_optimizer": false,
  "fp16": {
    "enabled": true,
    "auto_cast": false,
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "overlap_comm": false,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients": true,
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_prefetch_bucket_size": 5e8,
    "stage3_param_persistence_threshold": 1e6,
    "sub_group_size": 1e12,
    "elastic_checkpoint": true,
    "stage3_gather_16bit_weights_on_model_save": true,
    "ignore_unused_parameters": true,
    "round_robin_gradients": true
  }
}

`
@ssbuild 

大佬 deepspeed 的 模块好像有些问题，前几天还能跑起来，
最近几天突然就会卡主，一直卡在上面那种情况。

**Comment by ssbuild** [comment]
docker 创建容器，加个--shm_size参数，例如给10g

**Comment by weizhenzhao** [comment]
--shm_size 是什么东西呀？我是租的机器，本身就在docker里面，没有办法操作宿主机的参数呢。

**Comment by ssbuild** [comment]
> --shm_size 是什么东西呀？我是租的机器，本身就在docker里面，没有办法操作宿主机的参数呢。

容器共享内存小，跑不起来。

**Comment by weizhenzhao** [comment]
https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning

大佬如何看待清华开源的那个p_tuning
感觉清华的开源的那个数据集用的好像不是对话数据集呢
