### ISSUE TITLE
Loss到达多少是模型收敛状态？

### ISSUE THREAD

**Issue by leoluopy** [ssbuild/chatglm_finetuning#117]
使用 train.py 训练示例数据 ， config使用 config_small.json ， loss达到： loss=0.000718 。 随后使用 infer_finetuning.py 推理示例prompt 仍然结果不对。 这是哪里问题 ？ 模型欠拟合 ？

**Comment by ssbuild** [comment]
config_small.json 只是为了让体验训练过程， 请全参数，在自己的数据上面训练。

**Comment by leoluopy** [comment]
了解，我调整一下

**Comment by weizhenzhao** [comment]
@leoluopy 
- 感觉loss达到2以下 。1点7或者 1点8几  基本就可以生成正常的对话了。
- 还要注意数据集不要有重复次数出现太多的话语，这样会过拟合。
- 还要注意要28层全部训练，不然loss降低不到2以下的。
亲身经历。
@ssbuild 

- 不过还有一个问题，如果你全部都是对话 生成数据去训练。会有遗忘问题，就比如你让它写一个快速排序算法，它就会回答。“好以下是一个快速排序代码：”然后居然不给你输出代码。感觉这是遗忘问题。是不是要考虑一下用羊驼的数据格式加一个instruction。这样会不会好一点呀？

**Comment by leoluopy** [comment]
@weizhenzhao
谢谢分享

**Comment by nieallen** [comment]
> @leoluopy
> 
> * 感觉loss达到2以下 。1点7或者 1点8几  基本就可以生成正常的对话了。
> * 还要注意数据集不要有重复次数出现太多的话语，这样会过拟合。
> * 还要注意要28层全部训练，不然loss降低不到2以下的。
>   亲身经历。
>   @ssbuild
> * 不过还有一个问题，如果你全部都是对话 生成数据去训练。会有遗忘问题，就比如你让它写一个快速排序算法，它就会回答。“好以下是一个快速排序代码：”然后居然不给你输出代码。感觉这是遗忘问题。是不是要考虑一下用羊驼的数据格式加一个instruction。这样会不会好一点呀？

同感，不知道怎么解决这个遗忘问题，或许需要lora_rank降低一些？

**Comment by cristianohello** [comment]
@weizhenzhao 
同感，餐饮领域一万多条多轮对话数据，会出现遗忘情况。
但是，如果模型能记住这一万条微调数据也可以，不在这一万多条微调数据的问题，回答不受影响就好了！！！

**Comment by leoluopy** [comment]
@ssbuild
对于模型的遗忘问题，有啥解决建议吗？
