### ISSUE TITLE
loss一直不降低，一万多条餐饮领域多轮对话数据进行微调，参数该如何调

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#118]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name                                  | Type      | Params
--------------------------------------------------------------------
0 | _TransformerLightningModule__backbone | LoraModel | 6.9 B 
--------------------------------------------------------------------
58.7 M    Trainable params
6.9 B     Non-trainable params
6.9 B     Total params
27,721.957Total estimated model params size (MB)
Epoch 0:   6%|█████                                                                             | 1221/19937 [03:51<59:09,  5.27it/s, loss=3.3, v_num=0]
Epoch 0:   6%|████▉                                                                            | 1227/19937 [03:52<59:08,  5.27it/s, loss=3.11, v_num=0]
Epoch 0:   6%|█████                                                                            | 1240/19937 [03:55<59:05,  5.27it/s, loss=3.16, v_num=0]
Epoch 0:   6%|█████                                                                            | 1247/19937 [03:56<59:03,  5.27it/s, loss=2.84, v_num=0]
Epoch 0:   6%|█████                                                                            | 1252/19937 [03:57<59:02,  5.27it/s, loss=2.78, v_num=0]
Epoch 0:   6%|█████▏                                                                            | 1256/19937 [03:58<59:02,  5.27it/s, loss=2.9, v_num=0]
Epoch 0:   6%|█████                                                                            | 1259/19937 [03:58<59:01,  5.27it/s, loss=2.86, v_num=0]
Epoch 0:   6%|█████▏                                                                           | 1276/19937 [04:01<58:57,  5.27it/s, loss=3.15, v_num=0]
Epoch 0:   6%|█████▏                                                                           | 1282/19937 [04:03<58:59,  5.27it/s, loss=3.04, v_num=0]
Epoch 0:  10%|████████▏                                                                        | 2000/19937 [06:21<56:58,  5.25it/s, loss=3.37, v_num=0]INFO:root:epoch 0 ,step 2000 , save best 4.1875, ./best_ckpt

Epoch 0:  13%|██████████▊                                                                      | 2650/19937 [08:24<54:53,  5.25it/s, loss=3.37, v_num=0]

**Comment by cristianohello** [comment]
loss不降反增？

**Comment by weizhenzhao** [comment]
如果用的lion优化器，28层transformer的话，学习率改成2e-6 亲身经历，会下降的。
不过下降到最后 基本就开始波动了，不知道为啥它这个波动的很剧烈。不过如果用的是28层的话，会降到2以下 1以上。
生成的效果还算通顺，不过会有遗忘问题，比如写代码它就忘记了。

**Comment by gg22mm** [comment]
> 

28层用的多大的显呀啊，什么型号GPU

**Comment by nieallen** [comment]
> 如果用的lion优化器，28层transformer的话，学习率改成2e-6 亲身经历，会下降的。 不过下降到最后 基本就开始波动了，不知道为啥它这个波动的很剧烈。不过如果用的是28层的话，会降到2以下 1以上。 生成的效果还算通顺，不过会有遗忘问题，比如写代码它就忘记了。

我微调后忘得很厉害，轮次多了，生成回答都往微调数据的领域扯，轮次少了，不仅微调数据没学到，模型原有知识也变差了

**Comment by cristianohello** [comment]
@weizhenzhao 
我的loss下降到1.8左右
我在想是不是微调的一万的数据太少了？

**Comment by cristianohello** [comment]
@nieallen 
你这个轮次多了，生成回答都往微调数据的领域，模型回答的合理吗？合理的话也能接受吧，微调的目的就是往领域靠

**Comment by nieallen** [comment]
> @nieallen 你这个轮次多了，生成回答都往微调数据的领域，模型回答的合理吗？合理的话也能接受吧，微调的目的就是往领域靠

合理，但我希望能balance一些，聊领域相关就往领域靠，随便闲聊，就回答通用一些。
