### ISSUE TITLE
使用deepspeed stage2或3策略时，模型保存和预测都有问题，遇到存储时就卡住

### ISSUE THREAD

**Issue by ericperfect** [ssbuild/chatglm_finetuning#12]
使用deepspeed stage2或3策略时，模型保存和预测都有问题，遇到存储时就卡住

**Comment by ericperfect** [comment]
@ssbuild

**Comment by WaveLi123** [comment]
感谢大佬反馈，deepspeed stage 2设置下多机多卡加速比不太明显，大佬这块有测试过多机多卡性能吗？

**Comment by EnghishYang** [comment]
> 感谢大佬反馈，deepspeed stage 2设置下多机多卡加速比不太明显，大佬这块有测试过多机多卡性能吗？

你好，确实觉得加速不明显，方便透露一下您那边的训练速度（数据量和时间）吗，我这边感觉训的好慢。
