### ISSUE TITLE
这个要多大的gpu才行？我GeForce RTX3090 用全参数24G都不行

### ISSUE THREAD

**Issue by gg22mm** [ssbuild/chatglm_finetuning#121]
这个要多大的gpu才行？我GeForce RTX3090 用全参数24G都不行

以下配置如果是全参数的话需要40G的才能运行起来~~ ：
'config_name': './config/config.json'
'train_batch_size': 4,  #训练批次
    'eval_batch_size': 2,   #
    'test_batch_size': 2,

以下配置需要30多G的才能运行起来~~ ：
'config_name': './config/config.json'
'train_batch_size': 1,  #训练批次
    'eval_batch_size': 1   #
    'test_batch_size': 1,

25G以下的不用玩了...  你们不知道是怎么运行起来的，甚是奇怪...

**Comment by heyudage** [comment]
6张V100 32G，stage2勉强跑起来

**Comment by heyudage** [comment]
6张V100 32G，stage3，勉强跑起来

**Comment by gg22mm** [comment]
> 6张V100 32G，stage3，勉强跑起来

你这也太夸张了点，我是40G就可以跑起来了 ~~  ，我看没有没用更低硬件能跑起来的，学习学习~~！！

**Comment by heyudage** [comment]
> > 6张V100 32G，stage3，勉强跑起来
> 
> 
> 
> 你这也太夸张了点，成本得多少去，一张5个W, 30十个W起步吗~~，我是40G就可以跑起来了 ~~  ，我看没有没用更低硬件能跑起来的，学习学习~~！！
全参数的话确实显存要求高，lora的话貌似可以在单卡跑起来

**Comment by gg22mm** [comment]
> > > 6张V100 32G，stage3，勉强跑起来
> > 
> > 
> > 你这也太夸张了点，成本得多少去，一张5个W, 30十个W起步吗~~，我是40G就可以跑起来了 ~~  ，我看没有没用更低硬件能跑起来的，学习学习~~！！
> > 全参数的话确实显存要求高，lora的话貌似可以在单卡跑起来

开启lora是不是后面精度不高呢？我看好象意思是：保存loss最小权重。

还有我用全参数，设置个10层这样能跑起来，然后批次配置还可以用下面的
'train_batch_size': 4, #训练批次
'eval_batch_size': 2, #
'test_batch_size': 2,

**Comment by luieswww** [comment]
8G能跑起来的方案，参数设置怎么弄啊

**Comment by gg22mm** [comment]
> 8G能跑起来的方案，参数设置怎么弄啊

我也想知道， 我之前11G都没成功，我去网上找了个 GeForce RTX3090 来测试 24G，就是上面的效果。  单卡我看最大好就也就24G
