### ISSUE TITLE
请问chatglm有继续在领域纯文本上进行pretrain的方法吗？

### ISSUE THREAD

**Issue by calvinzhan** [ssbuild/chatglm_finetuning#124]
如果我在领域上有比较大量的领域纯文本，如何才能让chatglm适应领域，并进行问答呢？有没有像下方的chatllama中间步骤的类似方法，可以在纯文本上进行训练？或者有什么方法可以把纯文本巧妙地变成chatglm的训练集（不需要人工去生成的）？

![chatllama](https://user-images.githubusercontent.com/5028298/229395414-476326dd-e756-40e7-8034-31350ec05987.jpg)

**Comment by cristianohello** [comment]
+1

**Comment by IamRoBota** [comment]
把示例的 q a 对数据改成 q为空，a来放你预训练的文本  这样应该就ok吧

**Comment by ray075hl** [comment]
> 把示例的 q a 对数据改成 q为空，a来放你预训练的文本 这样应该就ok吧

不太理解， 预训练不是 q = text[:-1] , a = text[1:]   吗？  大佬给解释一下啊 @IamRoBota
