### ISSUE TITLE
请问训练数据的路径是在data_utils.py中修改吗？为什么训练中的输出看起来像是用了默认的json文件？

### ISSUE THREAD

**Issue by MEIZU16** [ssbuild/chatglm_finetuning#13]
<img width="375" alt="屏幕截图 2023-03-17 130242" src="https://user-images.githubusercontent.com/70087645/225817560-11525e54-3e58-4e64-85b7-427658c6b5da.png">
<img width="458" alt="屏幕截图 2023-03-17 130322" src="https://user-images.githubusercontent.com/70087645/225817566-bfecdc2a-e4f4-4b45-bc80-2dc8759956ca.png">
我把默认的json删了，重新训练还是这样

**Comment by ssbuild** [comment]
需要删除output缓存的record文件

**Comment by MEIZU16** [comment]
> @MEIZU16 需要删除output缓存的record文件

ok
