### ISSUE TITLE
回答质量的评价模型在哪里呢？如果没有实现，有计划吗？

### ISSUE THREAD

**Issue by leoluopy** [ssbuild/chatglm_finetuning#130]
如题

**Comment by ssbuild** [comment]
目前评估是自行生成语料， 修改 https://github.com/ssbuild/chatglm_finetuning/blob/main/evaluate.py 自行评估 。

**Comment by leoluopy** [comment]
如果想要提一些代码上来，如何开一个 pull request  ？

**Comment by ssbuild** [comment]
> 如果想要提一些代码上来，如何开一个 pull reques

首先是 将对方fork到自己GitHub账号来，然后克隆代码到本地电脑来，在本地电脑上修改好代码后，再push到自己的GitHub上上面，最后就可以直接创建pull request了。

**Comment by leoluopy** [comment]
好的，我先提一些工具性质的代码，后面再深入一些。
