### ISSUE TITLE
batch_size与训练步数

### ISSUE THREAD

**Issue by IamRoBota** [ssbuild/chatglm_finetuning#131]
大佬好，我600w数据，设置的train_batch_size=1, gradient_accumulation_steps=1, devices=2 (两张卡)， 但是跑起来的时候每个epoch显示需要训练150w步，不是应该总batch_size=train_batch_size * gradient_accumulation_steps * devices = 2, 每个epoch步数 = 600w / 总batch_size = 300w步吗？

请问还有什么设置影响batch_size呢 ？

谢谢

**Comment by ssbuild** [comment]
由于数据策略，真实数据数量可能并不是实际数据，https://github.com/ssbuild/chatglm_finetuning/blob/f4c21f1de1acb31f7a8c2b5c2b30ac8fe4f52d21/train.py#L162  ,  可以看看数据数量在计算下。

**Comment by IamRoBota** [comment]
> 由于数据策略，真实数据数量可能并不是实际数据，
> 
> https://github.com/ssbuild/chatglm_finetuning/blob/f4c21f1de1acb31f7a8c2b5c2b30ac8fe4f52d21/train.py#L162
> 
> , 可以看看数据数量在计算下。

大佬好， 我在这个函数里print了一下return时所用的limit_count，显示确实是600w条

**Comment by ssbuild** [comment]
> > 由于数据策略，真实数据数量可能并不是实际数据，
> > https://github.com/ssbuild/chatglm_finetuning/blob/f4c21f1de1acb31f7a8c2b5c2b30ac8fe4f52d21/train.py#L162
> > 
> > , 可以看看数据数量在计算下。
> 
> 大佬好， 我在这个函数里print了一下return时所用的limit_count，显示确实是600w条

在我给的例子里，例如300条 ，  batch_size = 4 , device=2  gradient_accumulation_steps=1 , steps = 37 正常

**Comment by ssbuild** [comment]
上传下配置信息

**Comment by IamRoBota** [comment]
> 

好的，您看下~

Training Args:
![Screenshot 2023-04-04 at 11 08 55](https://user-images.githubusercontent.com/15852871/229677491-bf0b726c-8b70-470e-b752-549954b62196.png)

**Comment by IamRoBota** [comment]
> 上传下配置信息

好的，您看下~

Training Args:
![Screenshot 2023-04-04 at 11 08 55](https://user-images.githubusercontent.com/15852871/229677659-728b9c4c-ec05-4ce1-b37a-e4663efa3f7e.png)

**Comment by ssbuild** [comment]
@IamRoBota 

pip list | grep -E "deep|torch"   然后上传下部分训练日志分析看看。

**Comment by IamRoBota** [comment]
> @IamRoBota
> 
> pip list | grep -E "deep|torch" 然后上传下部分训练日志分析看看。

pip list | grep -E "deep|torch"的输出：
![Screenshot 2023-04-04 at 14 03 49](https://user-images.githubusercontent.com/15852871/229702596-436e3351-8c3c-49ce-b10a-af6ac96b5d24.png)

我用下面这个配置在devices=1和devices=2分别实验了下，发现devices=1时步数600w, devices=2就直接变成150w(缩了1/4而不是1/2)。

参数配置：
（train_batch_size都是1）
![Screenshot 2023-04-04 at 14 06 38](https://user-images.githubusercontent.com/15852871/229703220-94180902-0417-47c9-9955-18d173adfb16.png)

Devices=1时log:

![Screenshot 2023-04-04 at 14 08 22](https://user-images.githubusercontent.com/15852871/229703372-0ca9382b-14e2-4c00-a4d5-4922246870ad.png)
![Screenshot 2023-04-04 at 14 06 53](https://user-images.githubusercontent.com/15852871/229703405-26e45f3e-6138-4a6f-af32-5c8fdf98c2d3.png)

Devices=2时log:

![Screenshot 2023-04-04 at 14 08 09](https://user-images.githubusercontent.com/15852871/229703536-ca47654e-66d4-4af3-8133-417929fbe99f.png)
![Screenshot 2023-04-04 at 14 05 42](https://user-images.githubusercontent.com/15852871/229703553-f66a6ec2-010e-4954-a1a1-33ff9078a502.png)

**Comment by ssbuild** [comment]
我用了600条了模拟了你这个实验 ， 还是无法复现你这个问题， 将代码安装最新的做做实验 。时间富裕了在模拟下600万条看看，

**Comment by cristianohello** [comment]
@IamRoBota @ssbuild 

devices=2 指的是第三张卡吧？也就是一张卡！参考这里的解释：https://github.com/ssbuild/chatglm_finetuning/issues/134

**Comment by cristianohello** [comment]
@IamRoBota 
你的数据组织格式是啥样的，方便发一条让我看看吗？

**Comment by IamRoBota** [comment]
> @IamRoBota @ssbuild
> 
> devices=2 指的是第三张卡吧？也就是一张卡！参考这里的解释：#134

不是吧兄弟 我这传的是int 2 不是list [2]

**Comment by xubuvd** [comment]
> @IamRoBota @ssbuild
> 
> devices=2 指的是第三张卡吧？也就是一张卡！参考这里的解释：#134

devices=2是有两张卡可用

**Comment by IamRoBota** [comment]
拉了最新代码后来ok了，谢谢大佬
