### ISSUE TITLE
有实验成功的大佬告知下，with_lora效果到底如何？

### ISSUE THREAD

**Issue by Chtholly1** [ssbuild/chatglm_finetuning#132]
个人用4w条领域内数据，用with_lora训练后，在预测时效果并不符合预期。
不知道是数据太少，还是可训练层数太少，还是with_lora本身效果就一般呢？
有无懂哥讲讲自己的实验效果，十分感谢！！

**Comment by Chtholly1** [comment]
> @Chtholly1 你的数据组织形式是什么？a键值对不能为空！

"a"里面不是空呀o(╥﹏╥)o

**Comment by Chtholly1** [comment]
> 训练层数有多少？

2080单卡训的 层数只有几层

**Comment by xubuvd** [comment]
> 

这个没效果的，我的2层，输出的都乱了，需要28层一起训练～
