### ISSUE TITLE
你好大佬，多轮对话的时候，response, history = model.chat()，中的history 作用是什么？如何在第二轮对话的时候利用上第一轮的对话结果q和a?

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#137]
你好大佬，多轮对话的时候，response, history = model.chat()，中的history 作用是什么？如何在第二轮对话的时候利用上第一轮的对话结果q和a?

比如：下面的例子：
 response, history = model.chat(tokenizer, "汽车保险杠有拳头大小的蹭伤，怎么补。没破，就是漆掉了", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=0.7, temperature=0.95,)
    print('汽车保险杠有拳头大小的蹭伤，怎么补。没破，就是漆掉了',' ',response)

    response, history = model.chat(tokenizer, "可以自己买喷喷吗", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=0.7, temperature=0.95,)
    print('可以自己买喷喷吗',' ',response)

第二个对话的history=[]  应该怎么写？

    response, history = model.chat(tokenizer, "可以自己买喷喷吗", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=0.7, temperature=0.95,)
    print('可以自己买喷喷吗',' ',response)

**Comment by ssbuild** [comment]
chat 函数会返回 history , 将返回的history  传入下一次chat函数即可

**Comment by hhy150** [comment]
请问这个history是不是我上一次提出的问题呢？

**Comment by ybshaw** [comment]
> 对， 根据自己的情况，控制下轮数或者自己截断， 一直输入容易爆炸。

尝试了3论对话，每轮对话的history都用第一次对话返回的history，结果24G 的机器在经过3轮对话后就OOM了，请问有什么解决办法吗，现在想在第一次对话时给模型一些先验知识，，然后在后续每次对话的history都用第一次对话返回的history，从而让模型掌握一些先验知识，但总是OOM
