### ISSUE TITLE
请问下如何解决多轮对话的情况下，数据会被打乱的情况

### ISSUE THREAD

**Issue by yuye2133** [ssbuild/chatglm_finetuning#139]
对话1:
a1: xxx
q1: yyy
a2: zzz
q2: tttt

看到这样的数据应该是做成了[(xxx, yyy), (xxx+yyy+zzz, tttt)]的数据集，这样的数据如果shuffle就丢掉了之前原本对话的顺序性，是否有影响呢

**Comment by ssbuild** [comment]
1. 制作训练数据打乱是按照 paragraph 打乱的， 也就是同一段对话不影响制作。
2. 训练时候也会打乱， 因为数据特征已经制作好，打乱不会受影响。

**Comment by songge25** [comment]
@yuye2133  请问下你的数据格式能给我参考一下吗，多轮的，一行就成
