### ISSUE TITLE
infer失败

### ISSUE THREAD

**Issue by Simon006** [ssbuild/chatglm_finetuning#14]
![image](https://user-images.githubusercontent.com/44133055/225830189-f0e9e576-55fe-410a-a775-0d33c1461967.png)
前面data_utils和train运行没有问题
但是这个infer.py运行不出同样的结果.
是什么原因呢

**Comment by ssbuild** [comment]
> ![image](https://user-images.githubusercontent.com/44133055/225830189-f0e9e576-55fe-410a-a775-0d33c1461967.png) 前面data_utils和train运行没有问题 但是这个infer.py运行不出同样的结果. 是什么原因呢

拉取最新的代码， 安装要求安装最新的 就可以了

**Comment by ssbuild** [comment]
1 拉取最新代码 2 增大参数 3 增大批次

**Comment by BestSongEver** [comment]
我使用with_lora=True训练后，
使用infer_lora_finetuing.py测试。
随便问了个问题(比如“你是谁”)，结果算法输出极其多的句子，里面除了最开始回答我的问题，还自问自答了十几个问题，停不下来。
想请问这是怎么回事呢，谢谢@ssbuild @sepilqi

**Comment by ssbuild** [comment]
@BestSongEver 


走到这一步 说明距离成功很近了，  只是没学到结束符 ， 建议训练更多epochs ， 让学习更充分。

**Comment by BestSongEver** [comment]
请问使用with_lora，需要改变学习率吗（默认是  'learning_rate': 5e-5）
