### ISSUE TITLE
lora训练效果loss振荡，效果很差

### ISSUE THREAD

**Issue by harvey1477** [ssbuild/chatglm_finetuning#140]
采用2万多的多任务数据微调，出现了灾难性的遗忘，通用指令能力下降了很多，训练loss也是振荡的，是需要精细化调参吗

**Comment by ssbuild** [comment]
1. 全层训练
2  lora 会出现一些遗忘， 不过要比ptv2 好 ， 建议多调参试试，
3. 另外自己创建模板脚本转换尝试
4. 资源充足尝试正常微调模式。
