### ISSUE TITLE
因为任务对话，结果大部分都是确定的，如何保证结果的唯一性，实际当中每一次预测推理都有不同的回答，怎么固定？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#142]
因为任务对话，结果大部分都是确定的，如何保证结果的唯一性，实际当中每一次预测推理都有不同的回答，怎么固定？

**Comment by cristianohello** [comment]
参数：do_sample=True, top_p=0.7, temperature=0.95 各是什么意思？
能通过这些参数控制结果的唯一性吗？？？

**Comment by ssbuild** [comment]
top_p=1.0 , top_k=1

**Comment by cristianohello** [comment]
@ssbuild 

top_p=1.0 , top_k=1。那么 temperature这么参数如何设置，才能固定输出呢？

**Comment by ssbuild** [comment]
> @ssbuild
> 
> top_p=1.0 , top_k=1。那么 temperature这么参数如何设置，才能固定输出呢？

例如   response, history = model.chat(tokenizer, "写一个诗歌，关于冬天", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=1.0, temperature=1,tok_k=1)
