### ISSUE TITLE
报错：RuntimeError: Internal: [MASK] is already defined

### ISSUE THREAD

**Issue by songsa1** [ssbuild/chatglm_finetuning#147]
![image](https://user-images.githubusercontent.com/42863413/230589135-7767b0eb-a3fb-4abd-8297-87bb3e7563d6.png)

原因可能是昨天ChatGLM-6B模型更新了导致的，请问这个一应该怎样解决

**Comment by ssbuild** [comment]
是的，4月07日 官方精简了词表和权重，配置已同步，建议重新下载权重信息 deep_training 最低要求 0.1.1

**Comment by bssbgax75894** [comment]
有两种方案：
