### ISSUE TITLE
为什么best_ckpt文件夹里面，没有保存的模型。

### ISSUE THREAD

**Issue by zjp78** [ssbuild/chatglm_finetuning#149]
best_ckpt文件夹里面只有config.json，没有保存的模型，导致运行infor_lora_finetune时报错，找不到文件。有人遇到同样的问题么。

**Comment by ssbuild** [comment]
1. lora   按照loss保存模型已注释， 因此保存的模型路径在 last_ckpt文件夹 ， 配置文件在best_ckpt , 复制best_ckpt config.json 到 last_ckpt,   修改infor_lora_finetune 代码路径即可。
2. 有时间会更新下路径
