### ISSUE TITLE
生成record报错

### ISSUE THREAD

**Issue by MEIZU16** [ssbuild/chatglm_finetuning#15]
(glmft) dspwasc@dspwasc:~/Public/chat/chatglm_finetuning$ python data_utils.py 
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /home/dspwasc/Public/.tmp/tmpzquf58br
INFO:torch.distributed.nn.jit.instantiator:Writing /home/dspwasc/Public/.tmp/tmpzquf58br/_remote_module_non_scriptable.py
/root/miniconda3/envs/glmft/lib/python3.10/site-packages/pytorch_lightning/utilities/seed.py:47: LightningDeprecationWarning: `pytorch_lightning.utilities.seed.seed_everything` has been deprecated in v1.8.0 and will be removed in v2.0.0. Please use `lightning_fabric.utilities.seed.seed_everything` instead.
  rank_zero_deprecation(
INFO:lightning_fabric.utilities.seed:Global seed set to 42
Traceback (most recent call last):
  File "/home/dspwasc/Public/chat/chatglm_finetuning/data_utils.py", line 236, in <module>
    model_args, training_args, data_args, lora_args = parser.parse_dict(train_info_args)
  File "/root/miniconda3/envs/glmft/lib/python3.10/site-packages/transformers/hf_argparser.py", line 370, in parse_dict
    raise ValueError(f"Some keys are not used by the HfArgumentParser: {sorted(unused_keys)}")
ValueError: Some keys are not used by the HfArgumentParser: ['target_dtype']

**Comment by ruleGreen** [comment]
<img width="963" alt="image" src="https://github.com/ssbuild/chatglm_finetuning/assets/26263128/a3d8223c-700b-4cdc-8cf8-46f45a56d133">
我这边出现另外一个奇怪的错误，生成数据到一半左右报错，不管是record还是lmdb

**Comment by ssbuild** [comment]
> <img alt="image" width="963" src="https://user-images.githubusercontent.com/26263128/237255937-a3d8223c-700b-4cdc-8cf8-46f45a56d133.png"> 我这边出现另外一个奇怪的错误，生成数据到一半左右报错，不管是record还是lmdb

pip list | grep - E "deep|datasets|torch"  看一下版本

**Comment by ruleGreen** [comment]
<img width="547" alt="image" src="https://github.com/ssbuild/chatglm_finetuning/assets/26263128/0d5d83f9-1607-4e09-840a-7a83256db774">

**Comment by ruleGreen** [comment]
> > <img alt="image" width="963" src="https://user-images.githubusercontent.com/26263128/237255937-a3d8223c-700b-4cdc-8cf8-46f45a56d133.png"> 我这边出现另外一个奇怪的错误，生成数据到一半左右报错，不管是record还是lmdb
> 
> pip list | grep - E "deep|datasets|torch" 看一下版本

我是deep_training 0.1.2.post0也有这个问题然后update了一下好像

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm_finetuning/blob/42bc21b3a3126c24de6ca6dc51c2d4a75dd0767b/data_processer.py#L34

你用的是老代码吧 ， 新的已经没缓存context_ids 这个字段了。

**Comment by ruleGreen** [comment]
> https://github.com/ssbuild/chatglm_finetuning/blob/42bc21b3a3126c24de6ca6dc51c2d4a75dd0767b/data_processer.py#L34
> 
> 你用的是老代码吧 ， 新的已经没缓存context_ids 这个字段了。

不是，新代码，我自己的业务逻辑，刚重新看了一下，前面构造数据的时候没有走这个验证逻辑，只有中间报错的这个走了这个验证逻辑

**Comment by ssbuild** [comment]
> > https://github.com/ssbuild/chatglm_finetuning/blob/42bc21b3a3126c24de6ca6dc51c2d4a75dd0767b/data_processer.py#L34
> > 
> > 你用的是老代码吧 ， 新的已经没缓存context_ids 这个字段了。
> 
> 不是，新代码，我自己的业务逻辑，刚重新看了一下，前面构造数据的时候没有走这个验证逻辑，只有中间报错的这个走了这个验证逻辑

这个是numpy 序列化反序列化 ， 保证每个字段都是numpy应该可以。

**Comment by ssbuild** [comment]
@ruleGreen 

写的时候是批次写入 ， 在内存积攒一定数据量才会 序列化 写入文件系统 ， 你这个错误应该就是 非numpy 引起的诊断错误、

**Comment by ruleGreen** [comment]
> @ruleGreen
> 
> 写的时候是批次写入 ， 在内存积攒一定数据量才会 序列化 写入文件系统 ， 你这个错误应该就是 非numpy 引起的诊断错误、

是这个问题，感谢！已经fix了
