### ISSUE TITLE
求问模型保存问题

### ISSUE THREAD

**Issue by IamRoBota** [ssbuild/chatglm_finetuning#151]
大佬好，我现在得到的每一个save step保存下来的形式是这样：
![Screenshot 2023-04-10 at 11 29 18](https://user-images.githubusercontent.com/15852871/230820085-5d5f8adb-439c-4712-90d1-6978a8b99226.png)
想要保存成hf官方的这种形式：
![Screenshot 2023-04-10 at 11 29 57](https://user-images.githubusercontent.com/15852871/230820146-3a8d0962-5d10-4ef7-9d9a-41db5f4963a0.png)
尝试用下面这个方式进行加载和保存：
![Screenshot 2023-04-10 at 11 33 01](https://user-images.githubusercontent.com/15852871/230820336-9e5628d9-d008-40fe-a51e-d8e5cd652ae4.png)
但是报这个错：
![Screenshot 2023-04-10 at 11 36 18](https://user-images.githubusercontent.com/15852871/230820637-bd259c48-5f13-43b6-8bbb-175098695dd6.png)

请问应该怎么转换模型权重保存呢？

**Comment by ssbuild** [comment]
见 https://github.com/ssbuild/chatglm_finetuning/blob/9bc98c65d81c87f45a48f13f8581ca624f453ea4/infer_finetuning.py#L62

调用 model.save_pretrained 即可

**Comment by IamRoBota** [comment]
> 见
> 
> https://github.com/ssbuild/chatglm_finetuning/blob/9bc98c65d81c87f45a48f13f8581ca624f453ea4/infer_finetuning.py#L62
> 
> 调用 model.save_pretrained 即可

谢谢老板^_^
