### ISSUE TITLE
你好，我想问一下，如何修改配置参数或者如何微调模型才能让模型记住多轮对话数据集中的问和回复？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#152]
我现在有四万多条多轮数据集，采用lora微调后之后，模型对于四万多条数据集中的问题，大部分没有记住，如何微调才能让模型记住？

**Comment by ssbuild** [comment]
1, 明显是欠拟合，建议增大训练epochs ， 监控loss
2. 建议按照readme.md 所说，安装依赖，下载官方精简权重

**Comment by cristianohello** [comment]
@ssbuild 
四万条多轮对话数据，训练了8个epoch，loss从7下降到2左右，就停止了。再加大epoch，loss还会下降吗

**Comment by cristianohello** [comment]
@ssbuild 
大佬，问一个非常重要的问题。我怀疑下面这个参数设置和最终效果有关系？

大佬，train_info_args的 'target_modules': ['query_key_value'], 和 'target_modules': ['dense','dense_h_to_4h','dense_4h_to_h','query_key_value']有什么区别？

**Comment by fangzhangmnm** [comment]
loss下降到多少比较好？0.5？

**Comment by lxw0109** [comment]
![image](https://github.com/ssbuild/chatglm_finetuning/assets/6135246/bc2302c2-10bc-47bc-a646-9392ee98def8)
为啥我这边的loss这么低（训练数据是阅读理解、推理、生成SQL三类数据，都是比较难的任务类型），效果依然很差（乱生成、灾难性遗忘）
乱生成感觉是欠拟合，但灾难性遗忘有这么严重，整不会了 T_T
