### ISSUE TITLE
继续求问模型保存问题。

### ISSUE THREAD

**Issue by zjp78** [ssbuild/chatglm_finetuning#153]
您好，直接python train.py方法，在last_ckpt文件夹里面：只有以下两个文件。
![image](https://user-images.githubusercontent.com/29000320/230837676-747948ab-bb4d-4b12-a14c-c25f8cdb6194.png)

训练正常训练，只是训练过程中模型貌似没有保存。将adapter_config.json, adapter_model.bin移到best_ckpt/里面，运行infer_lora_finetuing.py，效果奇差无比，根本就是乱输出。

这是什么原因呢。

**Comment by ssbuild** [comment]
欠拟合

**Comment by zjp78** [comment]
大佬，麻烦具体解释一下，欠拟合 重复是什么意思。
