### ISSUE TITLE
大佬，train_info_args的 'target_modules': ['query_key_value'], 和 'target_modules': ['dense','dense_h_to_4h','dense_4h_to_h','query_key_value']有什么区别？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#155]
大佬，问一个非常重要的问题。我怀疑下面这个参数设置和最终效果有关系？

train_info_args的 'target_modules': ['query_key_value'], 和 'target_modules': ['dense','dense_h_to_4h','dense_4h_to_h','query_key_value']有什么区别？
['dense','dense_h_to_4h','dense_4h_to_h','query_key_value']这个参数设置是不是要优于['query_key_value']？？？

**Comment by zjp78** [comment]
这不就指定微调层数么，以我的训练经验。多的，loss会下降的更低。

**Comment by cristianohello** [comment]
@zjp78 
你知道在垂直领域做微调，微调数据有4万条多轮对话数据。怎么设置参数才能让模型记住微调的4万条数据，同时又不影响chatglm其他对话的输出内容？？？
