### ISSUE TITLE
使用4.7更新之后的代码和权重 一直nan

### ISSUE THREAD

**Issue by IamRoBota** [ssbuild/chatglm_finetuning#159]
4.7号官方更新了词表和权重，于是重新下载了权重、拉了本仓库最新的代码，配置使用的跟之前版本跑通无误的代码一样的配置（学习率、batch size、优化器等），但是loss上来就一直nan，请问可能是什么问题呢？谢谢大佬

**Comment by ssbuild** [comment]
按照readme.md 所说，deep_training 升级到 0.1.1 即可。

**Comment by IamRoBota** [comment]
> 

大佬，使用的是0.1.1版本

**Comment by IamRoBota** [comment]
> 按照readme.md 所说，deep_training 升级到 0.1.1 即可。


大佬，使用的是0.1.1版本

**Comment by ssbuild** [comment]
> > 按照readme.md 所说，deep_training 升级到 0.1.1 即可。
> 
> 大佬，使用的是0.1.1版本

rm -rf output ,  检查下自己的参数， 如果loss nan, 请参考之前相关issue.

**Comment by IamRoBota** [comment]
> > > 按照readme.md 所说，deep_training 升级到 0.1.1 即可。
> > 
> > 
> > 大佬，使用的是0.1.1版本
> 
> rm -rf output 重新训练 , 检查下自己的参数， 如果loss nan, 试试参考之前相关issue.

大佬，之前的issue都参考了，应该问题不太一样。不过刚发现可能是因为模型啥也没生成导致的loss，我刚跑infer.py，使用的官方新的6b权重，结果对您给的“你好”和“晚上睡不着应该怎么办”这两个query  模型都只生成了两个空格。但是官方更新权重和词表之前的模型（老权重）我infer.py是正常输出的。

**Comment by ssbuild** [comment]
> 词表

那就不对了， 上传下train_info_args 看看

**Comment by IamRoBota** [comment]
> > 词表
> 
> 那就不对了， 上传下train_info_args 看看

您看下~   lora我没开，它的参数就没截了

![Screenshot 2023-04-11 at 11 26 04](https://user-images.githubusercontent.com/15852871/231048557-ee30150a-fc18-40e6-a772-7a83ee3c9194.png)

**Comment by ssbuild** [comment]
> > > 词表
> > 
> > 
> > 那就不对了， 上传下train_info_args 看看
> 
> 您看下~ lora我没开，它的参数就没截了
> 
> ![Screenshot 2023-04-11 at 11 26 04](https://user-images.githubusercontent.com/15852871/231048557-ee30150a-fc18-40e6-a772-7a83ee3c9194.png)

是否新权重文件都下载成功了呢 ， 如果新权重都ok 应该是没问题的。

**Comment by IamRoBota** [comment]
> 

谢谢大佬，既然这些参数没问题的话，那我重新下载一遍权重再试试~

**Comment by IamRoBota** [comment]
> > > > 词表
> > > 
> > > 
> > > 那就不对了， 上传下train_info_args 看看
> > 
> > 
> > 您看下~ lora我没开，它的参数就没截了
> > ![Screenshot 2023-04-11 at 11 26 04](https://user-images.githubusercontent.com/15852871/231048557-ee30150a-fc18-40e6-a772-7a83ee3c9194.png)
> 
> 是否新权重文件都下载成功了呢 ， 如果新权重都ok 应该是没问题的。


谢谢大佬，既然这些参数没问题的话，那我重新下载一遍权重再试试~

**Comment by IamRoBota** [comment]
> 

感谢大佬耐心回复，再重新下了权重就ok了，之前下的时候和传到服务器时有多次断掉重连可能文件有损坏- -
