### ISSUE TITLE
打开with_lora训练报错

### ISSUE THREAD

**Issue by Traceve** [ssbuild/chatglm_finetuning#16]
RuntimeError: expected scalar type Half but found Float
Epoch 0:   0%|          | 0/275 [00:01<?, ?it/s]

**Comment by ssbuild** [comment]
> RuntimeError: expected scalar type Half but found Float Epoch 0: 0%| | 0/275 [00:01<?, ?it/s]

检查 train_info_args 'target_dtype': '16'  ， 因为预训练权重精度为半精度， 请确认该参数

**Comment by Traceve** [comment]
十分感谢，已解决。

**Comment by zhaodice** [comment]
你好，请问 train_info_args 'target_dtype': '16'  应该如何修改呢?

**Comment by ssbuild** [comment]
> 你好，请问 train_info_args 'target_dtype': '16' 应该如何修改呢?

这个默认不用改

**Comment by zhaodice** [comment]
> > 你好，请问 train_info_args 'target_dtype': '16' 应该如何修改呢?
> 
> 这个默认不用改

我的报错和他一样，但是我不知道修改哪里才正常...

**Comment by ssbuild** [comment]
> > > 你好，请问 train_info_args 'target_dtype': '16' 应该如何修改呢?
> > 
> > 
> > 这个默认不用改
> 
> 我的报错和他一样，但是我不知道修改哪里才能用lora正常训练...

这个就是精度不匹配导致的，就像readme.md 所说 ，建议安装deep_training 0.0.19 ， chatglm_finetuning 代码拉取一下， 改下with_lora 应该可以直接跑lora 。

**Comment by zhaodice** [comment]
> 这个就是精度不匹配导致的，就像readme.md 所说 ，建议安装deep_training 0.0.19 ， chatglm_finetuning 代码拉取一下， 改下with_lora 应该可以直接跑lora 。

你好，目前是这样的（都是目前最新拉取最新git clone 然后pip install .的）
```
RuntimeError: expected scalar type Half but found Float
Epoch 0:   0%|          | 0/7180 [00:00<?, ?it/s]                                                                                                            
(venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ git pull
Already up to date.
(venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ pip show deep_training
Name: deep-training
Version: 0.0.19
Summary: an easy training architecture
Home-page: https://github.com/ssbuild/deep_training
Author: ssbuild
Author-email: 9727464@qq.com
License: Apache License 2.0
Location: /home/user/ext/ChatGLM-6B/venv/lib/python3.10/site-packages
Requires: fastdatasets, numpy, pytorch-lightning, scikit-learn, scipy, sentencepiece, seqmetric, six, sklearn, tfrecords, tqdm, transformers
Required-by: 
(venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ 
```

**Comment by ssbuild** [comment]
> > 这个就是精度不匹配导致的，就像readme.md 所说 ，建议安装deep_training 0.0.19 ， chatglm_finetuning 代码拉取一下， 改下with_lora 应该可以直接跑lora 。
> 
> 你好，目前是这样的（都是目前最新拉取最新git clone 然后pip install .的）
> 
> ```
> RuntimeError: expected scalar type Half but found Float
> Epoch 0:   0%|          | 0/7180 [00:00<?, ?it/s]                                                                                                            
> (venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ git pull
> Already up to date.
> (venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ pip show deep_training
> Name: deep-training
> Version: 0.0.19
> Summary: an easy training architecture
> Home-page: https://github.com/ssbuild/deep_training
> Author: ssbuild
> Author-email: 9727464@qq.com
> License: Apache License 2.0
> Location: /home/user/ext/ChatGLM-6B/venv/lib/python3.10/site-packages
> Requires: fastdatasets, numpy, pytorch-lightning, scikit-learn, scipy, sentencepiece, seqmetric, six, sklearn, tfrecords, tqdm, transformers
> Required-by: 
> (venv) user@calculator:~/ext/ChatGLM-6B/chatglm_finetuning$ 
> ```

sorry ,  修改下config/config_small.json  "precision": 16

**Comment by zhaodice** [comment]
解决了，感谢
