### ISSUE TITLE
求问关于官方fix eos_token

### ISSUE THREAD

**Issue by IamRoBota** [ssbuild/chatglm_finetuning#161]
看到官方在tokenizer_config.json和tokenization_chatglm.py中修改了eos_token和end_token，请问会有什么影响啊，用之前错误的文件训的模型就废了吗？

感谢🙏

**Comment by ssbuild** [comment]
对当前仓库没有影响，因为27号之后是强制改的eos_token_id

**Comment by IamRoBota** [comment]
> 对当前仓库没有影响，因为27号之后是强制改的eos_token_id

大佬，用官方这次修改之前的文件训练的模型需要停下，更新下文件重新训吗， 不更新重训的话会影响之后使用吗

**Comment by ssbuild** [comment]
> 用官方这次修改之前的文件训练的模型需要停下

只对dev 仓库有影响 ， 其他分支没影响 ， dev 会follow使用 最新的。

**Comment by IamRoBota** [comment]
> > 用官方这次修改之前的文件训练的模型需要停下
> 
> 只对dev 仓库有影响 ， 其他分支没影响 ， dev 会follow使用 最新的。

好的 感谢
