### ISSUE TITLE
现在很少直接微调，玩模板是趋势 ， 模板指的是什么格式？能举个多轮对话的例子吗？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#162]
大佬你说的：现在很少直接微调，玩模板是趋势 ， 可以研究研究模板 ， 自己造模板。
例如最简单的： q = "humun：{question}" , a="robot：{answer}"

能详细举个多轮对话的例子吗？
比如下面这种例子，如何设置成模板？：
{"id": 1, "paragraph": [
{"q": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "a": ["用电脑能读数据流吗？水温多少"]},
{"q": "95", "a": ["继续发动水温就高了？", "上下水管温差怎么样啊？空气是不是都排干净了呢？"]},
{"q": "是的。上下水管都好的", "a": ["那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！", "您好，先确定一下水循环是否正常，节温器有没有正常打开！如果都是好的，要检查风扇插头有没有电过来，如果有证明风扇是坏的，如果没有在继续查线路吧！"]}]}

**Comment by fangzhangmnm** [comment]
[
   {"query"="下面是一段有关【MyPrivateTaskIdentifier】的聊天记录\n问：长城h3风扇不转\n答：",
"label"="你可以买台新电脑亲"}
]
