### ISSUE TITLE
deep_training安装问题

### ISSUE THREAD

**Issue by Stark-zheng** [ssbuild/chatglm_finetuning#163]
为什么我在安装这个包的时候，有时候可以安装成功，有时候提示找不到？

**Comment by ssbuild** [comment]
应该跟pip 环境的仓库镜像有关系， 建议使用readme 说提供的安装方式，使用pypi官方仓库镜像 ，虽然慢点，但是可靠。

**Comment by Stark-zheng** [comment]
ERROR: Could not find a version that satisfies the requirement deep_training (from versions: none)
ERROR: No matching distribution found for deep_training
用readme里的方式还是会显示这样、、

**Comment by ssbuild** [comment]
> 

是的 torch 需要最低1.10，  建议使用 torch 1.13 或者 torch 2.x

**Comment by ssbuild** [comment]
> 但是我在torch1.12.0+cu113的环境里安装不了deep_training、、

如果实在无法安装， 请下载安装包自行安装。

**Comment by Stark-zheng** [comment]
下载安装包安装显示这个，有点看不懂、、、：
  ERROR: HTTP error 404 while getting http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/5fa/d320488aa69c7/fastdatasets-0.9.6-py3-none-any.whl#sha256=5fad320488aa69c7c76e7f78bda9ac042e7dc7c906f2a1ead6286c1cbbbe4d00 (from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/+simple/fastdatasets/) (requires-python:>=3, <4)
ERROR: Could not install requirement fastdatasets<=1,>=0.9.6 from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/5fa/d320488aa69c7/fastdatasets-0.9.6-py3-none-any.whl#sha256=5fad320488aa69c7c76e7f78bda9ac042e7dc7c906f2a1ead6286c1cbbbe4d00 (from deep-training==0.1.2) because of HTTP error 404 Client Error: Not Found for url: http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/5fa/d320488aa69c7/fastdatasets-0.9.6-py3-none-any.whl for URL http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/%2Bf/5fa/d320488aa69c7/fastdatasets-0.9.6-py3-none-any.whl#sha256=5fad320488aa69c7c76e7f78bda9ac042e7dc7c906f2a1ead6286c1cbbbe4d00 (from http://pypi-devpi-proxy-svc.kube-system:3141/root/pypi/+simple/fastdatasets/) (requires-python:>=3, <4)

**Comment by ssbuild** [comment]
请问您是操作系统呢 ， tfrecords 不支持mac
