### ISSUE TITLE
使用lora之后，在best_ckpt目录下只有config.json，为什么没有adapter_config.json文件？

### ISSUE THREAD

**Issue by lawrencelxy** [ssbuild/chatglm_finetuning#164]

**Comment by Stark-zheng** [comment]
请问可以把last_ckpt的权重和best_ckpt的配置文件指定到一个文件夹吗？公司的ai平台需要指定模型收集路径，如果整个项目全收集就太大了、、

**Comment by ssbuild** [comment]
> 请问可以把last_ckpt的权重和best_ckpt的配置文件指定到一个文件夹吗？公司的ai平台需要指定模型收集路径，如果整个项目全收集就太大了、、

已经修改lora权重保存至best_ckpt 目录 ， 请查看和 测试。

**Comment by Stark-zheng** [comment]
好的，感谢

**Comment by Stark-zheng** [comment]
您好，再问一下，看您更新的是dev分支，我用的是stable-vocab130528分支，看stable-vocab130528里面好像有保存最小loss模型到best_ckpt目录的逻辑？为什么我昨天跑的best_ckpt里也只有一个配置文件、、

**Comment by ssbuild** [comment]
> 为什么我昨天跑的best_ckpt里也只有一个配置文件

保存模型逻辑是根据loss 最小值保存到 best_ckpt ，根据训练步数保存最新到last_ckpt。 经过测试 last_ckpt 效果更好，因此不再根据loss值保存到best_ckpt。 我同步改一下vocab130528 分支。

**Comment by Stark-zheng** [comment]
好的，万分感谢～
