### ISSUE TITLE
deepspeed安装失败

### ISSUE THREAD

**Issue by xiaoxiaohuizaici** [ssbuild/chatglm_finetuning#175]
(py38) E:\pyprojects\deepspeed-0.9.0>python setup.py install
DS_BUILD_OPS=1
test.c
LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  One can disable async_io with DS_BUILD_AIO=0
 [ERROR]  Unable to pre-compile async_io
Traceback (most recent call last):
  File "setup.py", line 157, in <module>
    abort(f"Unable to pre-compile {op_name}")
  File "setup.py", line 51, in abort
    assert False, msg
AssertionError: Unable to pre-compile async_io

**Comment by LvShuaiChao** [comment]
这个deepspeed应该不支持Windows吧

**Comment by ssbuild** [comment]
不建议使用windows ， 如果还有问题参考下deepseed 仓库。
