### ISSUE TITLE
请问 data_uitils.py 里面，LoRA的配置。

### ISSUE THREAD

**Issue by ngbruce** [ssbuild/chatglm_finetuning#178]
请问一下，data_uitils.py 里面，lora模块的部分。
按照 readme，使用lora要把 “with_lora” 设为 True，而下面还有一个字段 'enable_lora'，默认为 None，请问这个字段需要设置吗？

**Comment by ssbuild** [comment]
enable_lora 不需要人工设置

**Comment by ngbruce** [comment]
好的，谢谢。
