### ISSUE TITLE
这个项目lora微调的效果为什么没有其他的好？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#179]
这个项目lora微调后记不住领域多轮对话，而https://github.com/mymusise/ChatGLM-Tuning这个项目是可以的。这是为什么？？？？？？都是基于chatglm+lora微调的！！！

**Comment by ssbuild** [comment]
一般新手都会遇到这种问题， 需要反复做实验，自己总结，调整参数在训练 。
