### ISSUE TITLE
最新版本训练，保存后的ckpt做infer仍然瞎生成

### ISSUE THREAD

**Issue by lianyixin** [ssbuild/chatglm_finetuning#18]
感觉应该是训练仍然有问题，num_layers=1和num_layers=28训练1到20个epoch，训练后的任何ckpt预测都不行，瞎生成，应该是训坏了；如果是加载原始预训练模型可以正常进行预测，结果正确；求指教！
![image](https://user-images.githubusercontent.com/22935032/226183226-5e4f7f54-af2b-4f88-8e10-92caf7959223.png)

**Comment by ssbuild** [comment]
> 感觉应该是训练仍然有问题，num_layers=1和num_layers=28训练1到20个epoch，训练后的任何ckpt预测都不行，瞎生成，应该是训坏了；如果是加载原始预训练模型可以正常进行预测，结果正确；求指教！ ![image](https://user-images.githubusercontent.com/22935032/226183226-5e4f7f54-af2b-4f88-8e10-92caf7959223.png)

需要删除output缓存record文件

**Comment by lianyixin** [comment]
@ssbuild 多谢及时的回复；我之前包括现在重新删除了output的所有内容；跑了一个num_layers=1, max_epoch=1，还是同样的问题：
![image](https://user-images.githubusercontent.com/22935032/226184563-25a40516-3307-4e7f-9afd-9dc96828ec31.png)
再次求教

**Comment by ssbuild** [comment]
> @ssbuild 多谢及时的回复；我之前包括现在重新删除了output的所有内容；跑了一个num_layers=1, max_epoch=1，还是同样的问题： ![image](https://user-images.githubusercontent.com/22935032/226184563-25a40516-3307-4e7f-9afd-9dc96828ec31.png) 再次求教

一层参数基本上相当于无， 你搞一个批次过分了啊

**Comment by lianyixin** [comment]
> 一

谢谢提醒；我试一试全量参数；按理说全量参数训练一个批次应该是合理的？多谢

**Comment by ssbuild** [comment]
> > 一
> 
> 谢谢提醒；我试一试全量参数；按理说全量参数训练一个批次应该是合理的？多谢

效果已经经过了验证， 你在下面多调参试试

**Comment by weizhenzhao** [comment]
我知道了，是因为作者默认给的example训练数据集，是把3通对话重复了N遍，扩展成了几十通，这样会有严重的过拟合问题，导致，不论怎么修改模型层数，和权重，训练结果都会乱生成，而且在训练的时候loss会很快的下降，我跑了8层，54GB显存，到1层十几GB显存，都会出现这个问题。

**Comment by weizhenzhao** [comment]
但是我觉得模型应该是没问题的。只是数据得自己造。还得保证多样性。

**Comment by weizhenzhao** [comment]
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/13706689/227283538-242b1fa9-c428-483b-9408-998175b00bfb.png">

1. @ssbuild 大佬，我是用lora 的方式，在两张48GB的A40上面，用example的对话训练了，10个epoch。

2. 但是第一个问题“写一个诗歌，关于冬天”还是会乱生成，如果设置生成的时候max_length为1024的话，就一直生成1020个“天”，然后我把第一个问题的top_p设置成了0.9，temperature设置成了0.5之后，效果就好了一点，好像默认chat接口的top_p是0.7的，temperature是0.9。
3. 想问下会出现一直重复生成，“天”是因为用lora方式训练的epoch=10太少了嘛？还是没有去调整温度和top_p呢？
4. 如果我要训练100万通对话用lora的话，那应该训练多少个epoch呢？或者loss应该下降到多少才可以呢？上图那个loss是1.2几。

**Comment by ssbuild** [comment]
> <img alt="image" width="1597" src="https://user-images.githubusercontent.com/13706689/227283538-242b1fa9-c428-483b-9408-998175b00bfb.png">
> 
> 1. @ssbuild 大佬，我是用lora 的方式，在两张48GB的A40上面，用example的对话训练了，10个epoch。
> 2. 但是第一个问题“写一个诗歌，关于冬天”还是会乱生成，如果设置生成的时候max_length为1024的话，就一直生成1020个“天”，然后我把第一个问题的top_p设置成了0.9，temperature设置成了0.5之后，效果就好了一点，好像默认chat接口的top_p是0.7的，temperature是0.9。
> 3. 想问下会出现一直重复生成，“天”是因为用lora方式训练的epoch=10太少了嘛？还是没有去调整温度和top_p呢？
> 4. 如果我要训练100万通对话用lora的话，那应该训练多少个epoch呢？或者loss应该下降到多少才可以呢？上图那个loss是1.2几。

感谢反馈 ， 看下代码更新时间，数据处理有一处截断bug， 拉取在训练试试看。

**Comment by lxw0109** [comment]
@weizhenzhao 请问胡乱生成的问题解决了吗?
