### ISSUE TITLE
Lora 微调后，输出 response 为空

### ISSUE THREAD

**Issue by ngbruce** [ssbuild/chatglm_finetuning#180]
进行 lora微调，数据集是项目默认的测试数据。
data_utils.py 里面参数 设置了 'with_lora' 和 'r' :

    'with_lora': True,  # 是否启用lora模块
    'inference_mode': False, # 推理模型, 不需要手动设置
    'r': 32,  # changed 
    'target_modules': ['query_key_value'],
    'target_dtype': '16',
    'lora_alpha': 32,
    # 'enable_lora': [True],
    'enable_lora': None, # None

执行 train.py 完成 20个 epoch
best_ckpt\ 目录下生成的文件应该是正常的，其中 adapter_model.bin 为 1026 KB
执行 infer_lora_finetuning.py 后，输出的内容为空：
![image](https://user-images.githubusercontent.com/68752507/232366173-12ba6104-17cb-49ff-b2e9-7afb8bbd1f66.png)
请问可能是什么原因呢？

**Comment by ssbuild** [comment]
全层训练，不要用small.

**Comment by ngbruce** [comment]
> 全层训练，不要用small.
修改了 data_utils.py 如下：
'config_name':'./config/config.json'
'r' 也按照原代码改回了8 

运行 train.py 时，在模型载入系统内存之后，然后执行到这个语句之后：
> 181 │   │   │   trainer.fit(pl_model, train_dataloaders=train_datasets)

爆显存了，理论上这个模型应该在微调时占用 13G左右的显存吧，不应该24G也爆的，请问是有别的什么地方要修改吗？
![image](https://user-images.githubusercontent.com/68752507/232370493-25e64ed3-cb23-475d-bdde-d8928e1db249.png)

**Comment by ssbuild** [comment]
> > 全层训练，不要用small.
> 
> 修改了 data_utils.py 如下： 'config_name':'./config/config.json' 'r' 也按照原代码改回了8
> 
> 运行 train.py 时，在模型载入系统内存之后，然后执行到这个语句之后：
> 
> > 181 │   │   │   trainer.fit(pl_model, train_dataloaders=train_datasets)
> 
> 爆显存了，理论上这个模型应该在微调时占用 13G左右的显存吧，不应该24G也爆的，请问是有别的什么地方要修改吗？ ![image](https://user-images.githubusercontent.com/68752507/232370493-25e64ed3-cb23-475d-bdde-d8928e1db249.png)

参考readme int高效训练
