### ISSUE TITLE
模型加载缺少lm_head

### ISSUE THREAD

**Issue by 447428054** [ssbuild/chatglm_finetuning#182]
您好，请问为什么添加这一行，不加载lm_head呢，我看加载的模型，lm_head不在named_parameters也不再named_buffers

_keys_to_ignore_on_load_missing = [r"lm_head.weight"]

**Comment by ssbuild** [comment]
你看的很仔细，it is  share layer  , so be in   _keys_to_ignore_on_load_missing .

**Comment by 447428054** [comment]
> _keys_to_ignore_on_load_missing

好的，加载完模型为什么不在named_parameters里面呢，这样不是不会被优化了嘛

share是跟哪一层share呢

**Comment by ssbuild** [comment]
对的 ， 可有可无~

**Comment by 447428054** [comment]
> 对的 ， 可有可无~

对了，这个share是跟什么share呀，在哪里有说明呢～

感觉并不应该是可有可无呢，其在最终输出那里，梯度优化应该影响最大来着～

**Comment by ssbuild** [comment]
> > 对的 ， 可有可无~
> 
> 对了，这个share是跟什么share呀，在哪里有说明呢～
> 
> 感觉并不应该是可有可无呢，其在最终输出那里，梯度优化应该影响最大来着～

按照你的理解 做做实验 ， 可能理解要跟随实验才能最终得到正确的理解。
