### ISSUE TITLE
除了lora还有没有其他办法可以降低训练时显存的占用量

### ISSUE THREAD

**Issue by leoluopy** [ssbuild/chatglm_finetuning#184]
除了lora以及减小模型，还有没有其他办法可以降低训练时显存的占用量？
哪些实践方法是比较有效的？

**Comment by ssbuild** [comment]
1. 冻结 N 层 修改models.py global_num_layers_freeze  
2. ptuning v2    
4. lora   
4. 正常微调

**Comment by leoluopy** [comment]
ptuning v2 和 lora 以及 冻结 N 层， 从经验上讲谁效果更好，或者哪些场景下更适合哪种方法 ？
