### ISSUE TITLE
如何实现全量推理

### ISSUE THREAD

**Issue by magnificent1208** [ssbuild/chatglm_finetuning#185]
感谢！

**Comment by ssbuild** [comment]
infer.py 推理预训练模型
 infer_finetuning.py 推理微调模型
 infer_lora_finetuning.py 推理lora微调模型

**Comment by magnificent1208** [comment]
> infer.py 推理预训练模型 infer_finetuning.py 推理微调模型 infer_lora_finetuning.py 推理lora微调模型

感谢回复

infer_finetuning.py  只能推理量化后的吗？想用fp16

**Comment by ssbuild** [comment]
可以量化也不量化 ， 对应简单修改下就可以了，有注释加上自己的理解改改。

**Comment by magnificent1208** [comment]
if not model.quantized:
    #     # 按需修改，目前只支持 4/8 bit 量化 ， 可以保存量化模型
        model.half().quantize(4).cuda().to(torch.device('cuda:0'))
        
      直接使用这个 会报 RuntimeError: Library cublasLt is not initialized
显存未满
