### ISSUE TITLE
HFValidationError:请问这个错误怎么解决

### ISSUE THREAD

**Issue by hkhkq** [ssbuild/chatglm_finetuning#189]
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 
'/data/nlp/pre_models/torch/chatglm/chatglm-6b'. Use `repo_type` argument if needed.

**Comment by ssbuild** [comment]
> 

手动下载权重 ， 然后修改对应路径。

**Comment by hkhkq** [comment]
> 

大哥能给下具体的操作方法吗？在哪里下载，怎么改路径

**Comment by ssbuild** [comment]
看下readme

**Comment by hkhkq** [comment]
tokenizer, config, _,_ = dataHelper.load_tokenizer_and_config(tokenizer_class_name=C   │
│   124 │   assert tokenizer.eos_token_id == 130005   这里错的

**Comment by ssbuild** [comment]
这个错误是官方更新词典造成的，重新下载权重词典等即可。

**Comment by hkhkq** [comment]
预训练权重我下了，这里可能我没弄对，这里放在哪里，怎么配置不清楚，麻烦再说详细点，多谢

**Comment by hkhkq** [comment]
> 这个错误是官方更新词典造成的，重新下载权重词典等即可。

RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), 
serialized.size())] 现在又报这个错了

**Comment by ssbuild** [comment]
> > 这个错误是官方更新词典造成的，重新下载权重词典等即可。
> 
> RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 现在又报这个错了

代码更新一下，删除 output 试试

**Comment by hkhkq** [comment]
> 
还是不行，权重我是拷贝到了这个目录/data/nlp/pre_models/torch/chatglm/chatglm-6b，才过了第一个错误，但是我看配置好像读的是THUDM/chatglm-6b 这里，但是没去这里读，感觉这个配置是不是弄错了。

**Comment by hkhkq** [comment]
> > > 这个错误是官方更新词典造成的，重新下载权重词典等即可。
> > 
> > 
> > RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 现在又报这个错了
> 
> 代码更新一下，删除 output 试试

还是不行，权重我是拷贝到了这个目录/data/nlp/pre_models/torch/chatglm/chatglm-6b，才过了第一个错误，但是我看配置好像读的是THUDM/chatglm-6b 这里，但是没去这里读，感觉这个配置是不是弄错了。
