### ISSUE TITLE
infer_lora_finetune.py问题

### ISSUE THREAD

**Issue by harvey1477** [ssbuild/chatglm_finetuning#19]
全参数微调推理infer_finetune.py没问题
adapter微调推理出现如下Log，有办法解决吗
Input length of input_ids is 789, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 791, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 793, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 795, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 797, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 799, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 801, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 803, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 805, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 807, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 809, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 811, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 813, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 815, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 817, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 819, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 821, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 823, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 825, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 827, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 829, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 831, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 833, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 835, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 837, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 839, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 841, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 843, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 845, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tok

**Comment by harvey1477** [comment]
改了一下lora layers源码可以消除这个log 正常推理 不知道是不是正常的操作
    def forward(self, x: torch.Tensor):
        def T(w):
            return w.T if self.fan_in_fan_out else w
        if self.merged:
            return F.linear(x, T(self.weight), bias=self.bias)
        else:
            result = F.linear(x, T(self.weight), bias=self.bias)
            # if self.r > 0:
            #     after_A = F.linear(self.lora_dropout(x), self.lora_A)
            #     after_B = F.conv1d(
            #         after_A.transpose(-2, -1), 
            #         self.lora_B.unsqueeze(-1), 
            #         groups=sum(self.enable_lora)
            #     ).transpose(-2, -1)
            #     result += self.zero_pad(after_B) * self.scaling

**Comment by ssbuild** [comment]
@harvey1477 

这不是个bug ，是因为历史长度+query长度 超过了 chat函数 ， 请按照需要修改chat函数最大长度， 或者在送给chat函数 做个判断拦截。

**Comment by ssbuild** [comment]
@harvey1477 

这不是个bug ，是因为历史长度+query长度 超过了 chat函数 ， 请按照需要修改chat函数最大长度， 或者在送给chat函数 做个判断拦截。

**Comment by harvey1477** [comment]
> @harvey1477
> 
> 这不是个bug ，是因为历史长度+query长度 超过了 chat函数 max_length ， 请按照需要修改chat函数最大长度， 或者在送给chat函数 做个判断拦截。建议deep_training 升级 到 0.0.18.post9 简化chat 生成函数。

感谢回复 该issure可以closed
