### ISSUE TITLE
单卡训练内存爆了，是不是单卡训不了

### ISSUE THREAD

**Issue by hkhkq** [ssbuild/chatglm_finetuning#191]
RuntimeError: CUDA out of memory. Tried to allocate 500.00 MiB (GPU 0; 23.88 GiB total capacity; 22.90 GiB already 
allocated; 330.75 MiB free; 22.96 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try

**Comment by ssbuild** [comment]
24g的话，玩lora 或者 ptv2吧

**Comment by hkhkq** [comment]
> 24g的话，玩lora 或者 ptv2吧

正常的需求多少呢？

**Comment by ssbuild** [comment]
> > 24g的话，玩lora 或者 ptv2吧
> 
> 正常的需求多少呢？

80G

**Comment by hkhkq** [comment]
> > > 24g的话，玩lora 或者 ptv2吧
> > 
> > 
> > 正常的需求多少呢？
> 
> 80G
'with_lora': True,  # 是否启用lora模块
这个改了以后还是内存不够，是啥原因呢

**Comment by ssbuild** [comment]
> > > > 24g的话，玩lora 或者 ptv2吧
> > > 
> > > 
> > > 正常的需求多少呢？
> > 
> > 
> > 80G
> > 'with_lora': True,  # 是否启用lora模块
> > 这个改了以后还是内存不够，是啥原因呢

batch size 改成1 ， 最大长度减小到 512 ， 删除 output , 应该可以跑。

**Comment by zyxdm** [comment]
@ssbuild 24g用lora进行微调，batch size 改成1，一开始能够训练，但是一个epoch中训练到8000多个样本时就又开始报out of memeory。为什么一开始GPU是够的，训练着就不够了？

**Comment by ssbuild** [comment]
> 

最大长度降低 ， 删除output 缓存 重新制作数据试试。
