### ISSUE TITLE
训练数据的格式问题

### ISSUE THREAD

**Issue by yc930401** [ssbuild/chatglm_finetuning#192]
请问这种场景可以吗？
fine tune时只有q没有a，比如我就想让模型读N篇论文，训练时没有问题和答案给它。每篇论文当作一个只有q没有a的训练数据。
然后训练好了模型以后，想问模型关于这N篇论文相关的问题，模型能解答嘛？

**Comment by ssbuild** [comment]
可以如下设置 q= [""] , a=“文本”  ，  修改下data_utils.py  'strategy': DataStrategy.doublesliding, 可以满足你这个需求。

**Comment by yc930401** [comment]
感谢感谢，我去试试
