### ISSUE TITLE
labels全为-100是对的吗

### ISSUE THREAD

**Issue by feiwuu638** [ssbuild/chatglm_finetuning#193]
训练数据嵌入之后，训练标签是值全为-100的向量，请问这是合理的吗？
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/26407951/233314565-874ac987-e950-49e0-a90f-5c8ee0a60af3.png">

**Comment by ssbuild** [comment]
是合理的，只是没显示全。so...
