### ISSUE TITLE
关于生成策略

### ISSUE THREAD

**Issue by IamRoBota** [ssbuild/chatglm_finetuning#199]
大佬好，对于每个q我需要生成多个不同的a，我尝试修改了生成函数的参数num_beams和num_return_sequences，发现返回数量是没问题，但是经常返回的多个a都是一模一样的字符串，偶尔有一两个不一样的。请问是参数调整有问题还是？
![Screenshot 2023-04-23 at 17 15 49](https://user-images.githubusercontent.com/15852871/233830884-95f40083-b7e4-4482-abb3-51edbec0da52.png)

生成示例：
q: 就是好想
a: ["跟你说说心里话", "跟你说说心里话", "抱抱你", "跟你说说心里话", "跟你说说心里话"]

**Comment by ssbuild** [comment]
这种情况 一般是欠拟合。

**Comment by IamRoBota** [comment]
> 这种情况 一般是欠拟合。

大佬，beam search我理解不是维护num_beams个不同的路径吗，也就应该是不同的句子呀？

**Comment by ssbuild** [comment]
> > 这种情况 一般是欠拟合。
> 
> 大佬，beam search我理解不是维护num_beams个不同的路径吗，也就应该是不同的句子呀？

你可以研究下beam search ， 属于贪心算法， 另外do_sample  = False.

**Comment by ssbuild** [comment]
@IamRoBota 
sorry 开始没get  ,  你的问题应该是需要将 do_sample 改成False

**Comment by IamRoBota** [comment]
> @IamRoBota 开始没get you , 你的问题应该是需要将 do_sample 改成False

谢谢大佬，设为False确实不重复了
