### ISSUE TITLE
只用部分层效果比较差？

### ISSUE THREAD

**Issue by ericperfect** [ssbuild/chatglm_finetuning#2]
在前7层上跑，连训练集都不收敛，正常现象吗？
![image](https://user-images.githubusercontent.com/52102789/225229226-8a805d09-87f9-488c-9f3a-1ef016a5edc0.png)

**Comment by githubofhuo** [comment]
请问您收敛的loss是多少

**Comment by ericperfect** [comment]
不好意思没描述清楚，loss没注意，但是通过生成的东西感觉没收敛，训练了大概20个epoch，预测的效果很差

**Comment by githubofhuo** [comment]
我也遇到了同样的问题，请问如何修改可以训练更多的层，比如全部的28层，谢谢

**Comment by ericperfect** [comment]
config 文件的num_layers

**Comment by ssbuild** [comment]
chatglm 参数量较大 ，词典也很大15万左右，尝试下全参数训练，训练更久一些看看效果，就loss 而言应该是收敛的 @githubofhuo @ericperfect

**Comment by BestSongEver** [comment]
目测该项目必火。
想请教一下：我用200条数据尝试微调，但在epoch 0 的“INFO:root:epoch 0 ,step 19 , save ./best_ckpt/best.pt”这一步就不动了，等两小时了。
![QQ图片2023031614024](https://user-images.githubusercontent.com/20766746/225529881-7f066608-8861-4cc4-bc5d-21cb713a4e3c.jpg)
请问这是在正常训练还是某种假死？我用了4张V100，微调选择了14层（刚改为1层，也这样）。GPU全一动不动的显示100%占用。
谢谢！ @ssbuild  @ericperfect

**Comment by BestSongEver** [comment]
> config 文件的num_layers

请教一下，我微调的layer数为2，为啥微调中以及微调后的infer，返回的response都是空呢？
Print出来的只有问题，没有回答。
谢谢！

**Comment by MEIZU16** [comment]
> > config 文件的num_layers
> 
> 请教一下，我微调的layer数为2，为啥微调中以及微调后的infer，返回的response都是空呢？ Print出来的只有问题，没有回答。 谢谢！@ericperfect

同样的问题，我的layer是8，也没有output

**Comment by BestSongEver** [comment]
> > > config 文件的num_layers
> > 
> > 
> > 请教一下，我微调的layer数为2，为啥微调中以及微调后的infer，返回的response都是空呢？ Print出来的只有问题，没有回答。 谢谢！@ericperfect
> 
> 同样的问题，我的layer是8，也没有output

我设置迭代次数多一点，后面出字了，但都是重复某个字或者词语的“乱码”，完全不能用。并且我看到训练过程中偶尔loss会出现nan
![企业微信截图_20230317102027](https://user-images.githubusercontent.com/20766746/225795697-717697cf-0268-4414-a4b8-2a833963f908.jpg)

**Comment by MEIZU16** [comment]
> > > > config 文件的num_layers
> > > 
> > > 
> > > 请教一下，我微调的layer数为2，为啥微调中以及微调后的infer，返回的response都是空呢？ Print出来的只有问题，没有回答。 谢谢！@ericperfect
> > 
> > 
> > 同样的问题，我的layer是8，也没有output
> 
> 我设置迭代次数多一点，后面出字了，但都是重复某个字或者词语的“乱码”，完全不能用。并且我看到训练过程中偶尔loss会出现nan ![企业微信截图_20230317102027](https://user-images.githubusercontent.com/20766746/225795697-717697cf-0268-4414-a4b8-2a833963f908.jpg)

是的，我多跑了几轮有字了，但都是乱七八糟的。话说这不是在6b模型上微调吗，为什么一点说话能力都没有，不太了解。

**Comment by archwolf118** [comment]
遇到了相同的问题。哪位大佬能解释一下，不胜感谢。

**Comment by jiwenbiao** [comment]
同样的疑惑，想问大约什么样的参数，数据量，epoch情况下，fintuning才回头收敛正常？

**Comment by VickyGit** [comment]
同样的问题，是数据集问题还是？感觉完全没有理解能力。

**Comment by ssbuild** [comment]
@VickyGit @jiwenbiao  使用最新的代码和安装要求。

**Comment by jiwenbiao** [comment]
> @VickyGit @jiwenbiao 使用最新的代码和安装要求。

看到了哈，之前应该是数据预处理padding那块有问题

**Comment by fourseven471** [comment]
> 

具体是哪里的padding的有问题呢，我用了最新的代码，还是有这个问题
