### ISSUE TITLE
您好，请问deep_training可以离线安装吗？

### ISSUE THREAD

**Issue by robin087** [ssbuild/chatglm_finetuning#20]
就是通过pip在线安装提示最新版只能获取到0.0.15的版本，请问要求的0.0.18版本可以离线安装吗？

**Comment by ssbuild** [comment]
可以离线安装 https://pypi.org/project/deep-training/#files  ， 不过你要手动下载依赖 ， pip 有 命令下载依赖，你调研一下。

**Comment by robin087** [comment]
好的，谢谢我去试一试

**Comment by ssbuild** [comment]
> 通过github内的requirement下载依赖，通过whl文件离线安装，是可行的

最简单的方法是 ， 在线安装到docker 镜像 ， 移动镜像就可以了。

**Comment by robin087** [comment]
> > 通过github内的requirement下载依赖，通过whl文件离线安装，是可行的
> 
> 最简单的方法是 ， 在线安装到docker 镜像 ， 移动镜像就可以了。

谢谢您的建议
