### ISSUE TITLE
整体微调，loss数值训练到第6，7轮左右为nan，各位大佬给看看啥原因

### ISSUE THREAD

**Issue by heiheiwangergou** [ssbuild/chatglm_finetuning#201]
这是我的配置
我是单张a100,14000条qa数据

<img width="599" alt="image" src="https://user-images.githubusercontent.com/45333312/234468438-77928732-7a4d-4926-8412-3b297bae0a0e.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/45333312/234468499-e42ef853-ed00-4b88-9e79-c07ebc0db79e.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/45333312/234468528-b4f28d1a-07be-4718-87d8-947dd2e9495f.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/45333312/234468785-8f8f1010-0e92-40b4-951e-03f54b35ae6d.png">

**Comment by ssbuild** [comment]
在训练epoch > 1 出现loss nan  一般做法学习率调小  增大batch。

**Comment by heiheiwangergou** [comment]
> 在训练epoch > 1 出现loss nan 一般做法学习率调小 增大batch。
大佬整体微调，loss要下降到多少才能用

**Comment by ssbuild** [comment]
经验 + 实验 自行操作吧。

**Comment by heiheiwangergou** [comment]
> 
要是使用多张卡微调的话，是不是device那里要改成跟你显卡个数一致

**Comment by ssbuild** [comment]
> 

对 ddp 或者 deepspeed 策略 根据自己的情况调整下。

**Comment by heiheiwangergou** [comment]
明白，有问题再请教您
