### ISSUE TITLE
大佬 ，能讲一下如何合并lora权重到原来的模型中吗？

### ISSUE THREAD

**Issue by chenyiwan** [ssbuild/chatglm_finetuning#203]
大佬 ，我这里训练出来了N个checkpoint,挑选了最好的一个lora.pt 文件 ，我想把它和原模型合并成一个新的模型文件。有没有办法呢？

**Comment by chenyiwan** [comment]
能讲一下思路吗？

**Comment by ssbuild** [comment]
参考下readme说明。

**Comment by realcarlos** [comment]
其实我比较好奇，为什么要把lora权重合并进去

**Comment by chenyiwan** [comment]
> 



> 其实我比较好奇，为什么要把lora权重合并进去

是这样的，我们有一部分领域知识训练了一部分，效果还可以，但现在还没训练完呢。所以我想保存这一部分，下次接着这个进度继续 训练啊。

> 其实我比较好奇，为什么要把lora权重合并进去

**Comment by realcarlos** [comment]
> > 
> 
> > 其实我比较好奇，为什么要把lora权重合并进去
> 
> 是这样的，我们有一部分领域知识训练了一部分，效果还可以，但现在还没训练完呢。所以我想保存这一部分，下次接着这个进度继续 训练啊。
> 
> > 其实我比较好奇，为什么要把lora权重合并进去

如果分别加载，这样与合并进去的推理效果是否一样呢？
