### ISSUE TITLE
训练效果不佳，咨询训练集问题

### ISSUE THREAD

**Issue by VickyGit** [ssbuild/chatglm_finetuning#21]
大佬，请教一下。目前没有较多的数据。只是想验证一下整体微调的效果。
尝试将数量3个数据通过make_data_example.py重复5000次作为训练集。
但训练8层数据感觉整体效果不佳。
想问：
是不是由于训练集数据的问题，如果是大概要提供多大的训练集，能否提供测试训练集参考学习。谢谢大佬
@ssbuild @sepilqi

**Comment by ssbuild** [comment]
1. 拉取最新代码  2  删除换成output文件夹 record  3 增大参数量 增大训练批次 。 如果前三个都做好了 效果应该还可以的。

**Comment by VickyGit** [comment]
> 
所以不是训练集的问题是吗？
增大参数量，指的是是num_layers层数吗，设置成28层？
训练批次max_epochs 20次还需要调整吗。
小白，麻烦大佬多多指正。

**Comment by ssbuild** [comment]
只能说，参数不全的话对微调训练集有效果，对于训练集以外的应该效果不佳，尽快全参数微调，实在不行lora

**Comment by VickyGit** [comment]
> 只能说，参数不全的话对微调训练集有效果，对于训练集以外的应该效果不佳，尽快全参数微调，实在不行lora

大佬，想确认下，是直接开28层训练吗？

**Comment by ssbuild** [comment]
> > 只能说，参数不全的话对微调训练集有效果，对于训练集以外的应该效果不佳，尽快全参数微调，实在不行lora
> 
> 大佬，想确认下，是直接开28层训练吗？

你可以用官方的推理测一下 ， 不是全参数是推理不出来结果 ， 建议全参数。
