### ISSUE TITLE
Deepspeed stage3保存模型权重维度为0

### ISSUE THREAD

**Issue by Jong-Won** [ssbuild/chatglm_finetuning#212]
deepspeed stage 3训练后，在模型文件权重矩阵维度为0：zero_pp_rank_0_mp_rank_00_model_states.pt
transformer.transformer.word_embeddings.weight : torch.Size([0])
transformer.transformer.layers.0.input_layernorm.weight : torch.Size([0])
transformer.transformer.layers.0.input_layernorm.bias : torch.Size([0])

**Comment by ssbuild** [comment]
参考infer_finetuning.py 关于权重介绍

**Comment by Jong-Won** [comment]
谢谢！忘记进行`python zero_to_fp32.py . best.pt`
