### ISSUE TITLE
请问一下，mac系统装不了deep_training？

### ISSUE THREAD

**Issue by WHJTC** [ssbuild/chatglm_finetuning#217]
The conflict is caused by:
    fastdatasets 0.9.7.post0 depends on tfrecords<0.3 and >=0.2.6
    fastdatasets 0.9.7 depends on tfrecords<0.3 and >=0.2.6

**Comment by ssbuild** [comment]
tfrecords不支持mac  ， 下一步开发计划解耦tfrecords 。
