### ISSUE TITLE
请教关于 get_mask() 和 get_position_ids()

### ISSUE THREAD

**Issue by sijeh** [ssbuild/chatglm_finetuning#23]
大佬，想请教一下 [get_mask](https://github.com/ssbuild/deep_training/blob/1783ba61e6ac025263cfe0461f7c8c30197185c7/nlp/models/chatglm/__init__.py#L807) 和 [get_position_ids](https://github.com/ssbuild/deep_training/blob/1783ba61e6ac025263cfe0461f7c8c30197185c7/nlp/models/chatglm/__init__.py#L819)  这里都是用batch 中的第1个样本计算`mask`和`position_ids`，如果训练时`batch_size`大于1 的话，这样操作也是可以的么？

**Comment by ssbuild** [comment]
具体 参考下glm模型

**Comment by sijeh** [comment]
> 

指的是chatglm的代码么？那个也是这么做的，但是推理的话(bz = 1)似乎也没毛病，如果训练的话，是不是要把这两个函数放到 dataset里面，对每一个sample生成不同的mask和 position_ids?
