### ISSUE TITLE
您好，请问可以支持模型分布式吗？

### ISSUE THREAD

**Issue by robin087** [ssbuild/chatglm_finetuning#24]
我使用的是V100 16G的显卡，在全参数的情况下无法训练，请问可以进行模型分布式将参数分到多个卡上进行训练吗？

**Comment by ssbuild** [comment]
多机器 ， 应该需要修改两个地方 Tranner 喂个参数num_nodes = 主机数 ， 另一个 就是 数据均衡 函数 host_num = 主机数， 请测试。
