### ISSUE TITLE
请问train.py能用来做continue pretrain吗？

### ISSUE THREAD

**Issue by acadaiaca** [ssbuild/chatglm_finetuning#25]
如果有大量的无标记领域文本（如新闻、wiki等），可以用来对train.py做继续预训练吗，对每层的权重进行微调吗？

**Comment by ssbuild** [comment]
可以，那这样模型生成就会更偏重于新数据了

**Comment by acadaiaca** [comment]
谢谢！如果是使用无标记数据，那输入的q和a怎么设定呢？

**Comment by ssbuild** [comment]
> 谢谢！如果是使用无标记数据，那输入的q和a怎么设定呢？

可以将 a 置空 ，修改 https://github.com/ssbuild/chatglm_finetuning/blob/9972f34716e26bcd6af0160f28cfbc8d00ffd69a/data_utils.py#L115
text = "[Round {}]\n问：{}\n答：{}".format(sid, q, a)  改为 text = q  即可
