### ISSUE TITLE
请问目前除了支持lora微调，还支持6B原始结构的微调吗？

### ISSUE THREAD

**Issue by lulia0228** [ssbuild/chatglm_finetuning#26]
看到chatGLM 6B有修正glm编码方式，结构调整

**Comment by lulia0228** [comment]
> 支持

Thanks for your reply? Can it support pretrain now?

**Comment by ssbuild** [comment]
Yes ,Of course,

**Comment by lulia0228** [comment]
> Yes ,Of course,

Bravo~！ I  will try it!
