### ISSUE TITLE
微调lora时发现loss上涨

### ISSUE THREAD

**Issue by jkl375** [ssbuild/chatglm_finetuning#28]
按照完整参数微调lora，发现loss刚开始下降到0.几，后来上升到3左右，是否需要调整学习率？
![image](https://user-images.githubusercontent.com/54523287/226331980-3fd6f09b-1b5e-4fb0-9359-c1df094120d7.png)

**Comment by ssbuild** [comment]
lora建议 学习率 5e-3  ，epoch 为正常训练10倍 ， 纯属经验值仅供参考。

**Comment by jkl375** [comment]
我昨天尝试了lr=5e-3，发现loss直接为nan
![image](https://user-images.githubusercontent.com/54523287/226499924-293ae36f-4c35-4768-a326-924905be1ec0.png)
后降为2e-5，发现20个epoch后，loss降到1.3，但是推理效果还行

**Comment by ssbuild** [comment]
> 我昨天尝试了lr=5e-3，发现loss直接为nan ![image](https://user-images.githubusercontent.com/54523287/226499924-293ae36f-4c35-4768-a326-924905be1ec0.png) 后降为2e-5，发现20个epoch后，loss降到1.3，但是推理效果还行

nice , Just experience value, everything from set out actually

**Comment by civi-code** [comment]
> 

请问跑全参数gpu大概需要多少显存

**Comment by BestSongEver** [comment]
我也是loss 先小后涨。
请问你微调的数据有多少条？@jkl375

**Comment by ssbuild** [comment]
请参考 #30
