### ISSUE TITLE
加入这个开源项目

### ISSUE THREAD

**Issue by leoluopy** [ssbuild/chatglm_finetuning#29]
感谢你的开源精神，这个项目在快速推进中，可以加入吗 ？ 盼复

**Comment by ssbuild** [comment]
感谢，已经邀请参与这个项目，欢迎一起为开源奉献。

**Comment by leoluopy** [comment]
加个微信，拉个开源贡献群，干起来？  我的微信 leoluopy

**Comment by ssbuild** [comment]
@leoluopy 

建议改下评论，隐藏私人微信， 有个群 185144988  欢迎.

**Comment by leoluopy** [comment]
@ssbuild  QQ群吗 ？ 可以也拉一个微信群不 ？
