### ISSUE TITLE
微调过程中loss=nan

### ISSUE THREAD

**Issue by githubofhuo** [ssbuild/chatglm_finetuning#3]
![image](https://user-images.githubusercontent.com/16174341/225230965-b3cb1226-7dfe-463c-b236-8e2dafc1e26e.png)

**Comment by BestSongEver** [comment]
> ![image](https://user-images.githubusercontent.com/16174341/225230965-b3cb1226-7dfe-463c-b236-8e2dafc1e26e.png)
> 

我也是这样，微调过程中偶尔伴随loss=nan。并且给出的output就是在重复某个字或者词
是不是意味着微调部分层是行不通的？@githubofhuo 
 或者有没有可能用于微调的数据的组织形式之类的存在问题@ssbuild

**Comment by githubofhuo** [comment]
> > ![image](https://user-images.githubusercontent.com/16174341/225230965-b3cb1226-7dfe-463c-b236-8e2dafc1e26e.png)
> 
> 我也是这样，微调过程中偶尔伴随loss=nan。并且给出的output就是在重复某个字或者词 是不是意味着微调部分层是行不通的？@githubofhuo 或者有没有可能用于微调的数据的组织形式之类的存在问题@ssbuild

我测试微调1层和7层都会有loss=nan

**Comment by manateeniu** [comment]
同微调nan，是数据制作有问题么

**Comment by VickyGit** [comment]
可以尝试调整一下学习率。但我目前训练结果也是一样，loss很低了，但答案还是一堆重复的字体。

**Comment by VickyGit** [comment]
@ssbuild 大佬能帮忙看看吗。是训练集合问题还是损失函数有选择有问题。

**Comment by jiwenbiao** [comment]
同问，fintuning 后面epcho 出现 loss=nan 的情况，具体效果还没测试

**Comment by ssbuild** [comment]
使用最新代码和安装要求，境外训练参数尽可能调大。

**Comment by lulia0228** [comment]
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/49608151/226830784-73e6e84a-384a-419c-b861-4693c9f72087.png">
6000多条数据 微调也出现nan了，一开始loss 4~7 然后就nan了，我的是config.num_layese=28层,其他参数没动。

**Comment by ssbuild** [comment]
> 的是config.num_layese=28层,其他参数没动。

学习率 调小 2e-5 或者再小点， 调调看。

**Comment by lulia0228** [comment]
> > 的是config.num_layese=28层,其他参数没动。
> 
> 学习率 调小 2e-5 或者再小点， 调调看。

<img width="423" alt="image" src="https://user-images.githubusercontent.com/49608151/226837294-59ea30cd-0c41-4d86-aaba-468cd1d35a25.png">
epoch0  未结束  loss突然就陡增了

**Comment by ssbuild** [comment]
> > > 的是config.num_layese=28层,其他参数没动。
> > 
> > 
> > 学习率 调小 2e-5 或者再小点， 调调看。
> 
> <img alt="image" width="423" src="https://user-images.githubusercontent.com/49608151/226837294-59ea30cd-0c41-4d86-aaba-468cd1d35a25.png">
> 
> epoch0 未结束 loss突然就陡增了

观测loss 走势看下最终情况 ，另外切换adamw 优化器试试

**Comment by lulia0228** [comment]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/49608151/227108256-14f706af-071f-4e1e-be34-d29c0a6b6e09.png">
调小学习率也不收敛
