### ISSUE TITLE
分布式训练速度慢的问题

### ISSUE THREAD

**Issue by zy234** [ssbuild/chatglm_finetuning#36]
你好，目前我用的是7张32G v100的卡，用deepspeed进行分布式训练，batchsize为4，这种训练速度是正常的么。
![image](https://user-images.githubusercontent.com/35094424/226535506-e9a72928-0137-4662-b272-1d030f36fe2e.png)
看起来要训练一轮需要30多个小时，这方面有哪些地方可以优化呢？

**Comment by ssbuild** [comment]
适当增大滑动窗口 但要小于最大长度， 最好设置 2 / 3 * max_length

**Comment by ray075hl** [comment]
@zy234 你好，请问你用的是模型并行的方式吗

**Comment by WaveLi123** [comment]
> 你好，目前我用的是7张32G v100的卡，用deepspeed进行分布式训练，batchsize为4，这种训练速度是正常的么。 ![image](https://user-images.githubusercontent.com/35094424/226535506-e9a72928-0137-4662-b272-1d030f36fe2e.png) 看起来要训练一轮需要30多个小时，这方面有哪些地方可以优化呢？

麻烦问下是全参数训练吗？deepspeed config可以分享下吗

**Comment by zy234** [comment]
@ssbuild 滑动窗口指的的data_utils里的 stride 吗

**Comment by zy234** [comment]
@ray075hl 是的，就是deepspeed的，这个大佬已经写好了。@WaveLi123 参数的话在zero_optimization里添加了这个字段，段"offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        }

**Comment by ray075hl** [comment]
@zy234 感谢回复， 请问你的pytorch 和 pytorch_lightning等其他的版本是什么啊， 我一直没微调成功；
```
  File "/opt/conda/envs/llm/lib/python3.8/site-packages/deep_training/nlp/layers/lora/layers.py", line 264, in forward
    after_B = F.conv1d(
RuntimeError: GET was unable to find an engine to execute this computation
```

**Comment by ssbuild** [comment]
> @zy234 感谢回复， 请问你的pytorch 和 pytorch_lightning等其他的版本是什么啊， 我一直没微调成功；
> 
> ```
>   File "/opt/conda/envs/llm/lib/python3.8/site-packages/deep_training/nlp/layers/lora/layers.py", line 264, in forward
>     after_B = F.conv1d(
> RuntimeError: GET was unable to find an engine to execute this computation
> ```
是你的cudnn 和 pytorch 不搭配， 我以为你已经看到答案了

**Comment by ray075hl** [comment]
@ssbuild    感谢大佬，我再去试试。

**Comment by Chenzongchao** [comment]
> 适当增大滑动窗口 但要小于最大长度， 最好设置 2 / 3 * max_length

这在哪里设置

**Comment by ssbuild** [comment]
@zy234 @Chenzongchao data_utils里的 stride 滑动窗口

**Comment by zy234** [comment]
@ssbuild 感谢回复。看起来这个是数据处理方面的优化，有模型方面的优化么，我看GPU的利用率一直上不去，是本身deepspeed 数据传输的限制么。

**Comment by ssbuild** [comment]
> @ssbuild 感谢回复。看起来这个是数据处理方面的优化，有模型方面的优化么，我看GPU的利用率一直上不去，是本身deepspeed 数据传输的限制么。

看到你把优化器放到cpu了， 由于你的硬件限制   牺牲时间换区空间 ，很无奈。

**Comment by ray075hl** [comment]
我用4个22g的p40，跑不了全参数的微调....... 但是config_small.json可以跑， 那就是说显存还是不够？ @ssbuild

**Comment by ray075hl** [comment]
我看infer的时候大概消耗了13g的显存batch_size=1；如果训练估计是40多个g；  @ssbuild  大佬，想请教一下，这个6B的模型微调大概需要多大的显存（在batch size为1、 config.json的情况下）

**Comment by zy234** [comment]
@ssbuild 感觉这个显存占用的太高了，6B的模型用了7张32G显存的都不够。。我们尝试了10B的GLM模型都能跑，batch还开的比这个大。
