### ISSUE TITLE
ddp 2卡显存占用疑问

### ISSUE THREAD

**Issue by lulia0228** [ssbuild/chatglm_finetuning#39]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/49608151/226794634-93c78d3b-8c7c-40ab-bd54-9b7c9e61ff43.png">

请教下，ddp数据并行，是不是应该2块卡上都有模型 看着只有一块卡的显存正常。

**Comment by ssbuild** [comment]
请确认下 这个是稳定后的状态吗

**Comment by lulia0228** [comment]
> 请确认下 这个是稳定后的状态吗

就是目前自带的270多条数据 训练了好几个epoch后的状态，回头换大的数据再观察一下。

**Comment by lulia0228** [comment]
> 请确认下 这个是稳定后的状态吗

> > 请确认下 这个是稳定后的状态吗
> 
> 就是目前自带的270多条数据 训练了好几个epoch后的状态，回头换大的数据再观察一下。

再次确认了下，torch.cuda.device_count() = 2  strategy = 'ddp' ; 换了600多条数据，稳定了，只有0卡显存77556MiB / 81251MiB 使用率打满； 1卡显存0，使用率0，上面的图1卡有些使用率是别人在用。

**Comment by lulia0228** [comment]
export CUDA_VISIBLE_DEVICES="1" && python infer_finetuning.py    代码还是会运行到0卡上，可能跟上面ddp不能多卡有关系

**Comment by lulia0228** [comment]
ddp 2卡 需要把data_utils.py中device改成2 吗？起来的瞬间好像有2个pid 过一会儿就剩一个了

**Comment by ssbuild** [comment]
try   CUDA_LAUNCH_BLOCKING=1 python train.py

**Comment by lulia0228** [comment]
> 
还是不行
