### ISSUE TITLE
About the data for fine-tuning

### ISSUE THREAD

**Issue by BestSongEver** [ssbuild/chatglm_finetuning#4]
感谢您优秀的工作！
想请教两个问题:
1.fine-tuning该模型的合理数据量需要多少？(比如您提供的示例QA数据对需要多少对)
2.您有开源的数据集、或者推荐的开源数据集可供fine-tune吗？数据的行业、内容无所谓，我主要想先实践一下fine-tune流程。
谢谢！@ssbuild @sepilqi

**Comment by ssbuild** [comment]
根据我的经验， 百万对以上，相对越多越好
