### ISSUE TITLE
对话数据中sptoken插入的位置

### ISSUE THREAD

**Issue by thinksoso** [ssbuild/chatglm_finetuning#41]
在这里sptoken插入的位置是随机生成的，请问为什么这么做，如果sptoken随机的位置不在对话轮次的开始位置，是不是会有负面效果
https://github.com/ssbuild/chatglm_finetuning/blob/bd84b4533d413c4f54a7bb8b071803b8bc8ae3c8/data_utils.py#L221

**Comment by ssbuild** [comment]
不会， 这样效果更好， 这不是 decoder-only , 建议看看glm 论文.
