### ISSUE TITLE
data_untils.py文件的一个qa数据处理方式不理解

### ISSUE THREAD

**Issue by expresschen** [ssbuild/chatglm_finetuning#42]
1. 在on_data_process函数中，一个qa样本被stride分割成几个qa样本，这个做的好处是什么
2. 在collate_fn函数中，随机 一个p，然后前面做输入，后面的做输出，感觉好奇怪

**Comment by ssbuild** [comment]
1. History memory session 2. GLM decoder p should be fixed in the head.

**Comment by SpongebBob** [comment]
这个看起来不是很科学，无法与原始的chatglm保持一致，这样会导致需要手动阶段预测阶段的ansewer，从一串多轮qa中抠出来

**Comment by ssbuild** [comment]
> 

你是对的， 准备按照官方构造数据 构造下。
