### ISSUE TITLE
infer.py为什么会出现如下错误?

### ISSUE THREAD

**Issue by June-Li** [ssbuild/chatglm_finetuning#43]
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpkmbp2ebc
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpkmbp2ebc/_remote_module_non_scriptable.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /root/miniconda3/envs/torch_1.13 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.7/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/pytorch_lightning/utilities/seed.py:47: LightningDeprecationWarning: `pytorch_lightning.utilities.seed.seed_everything` has been deprecated in v1.8.0 and will be removed in v2.0.0. Please use `lightning_fabric.utilities.seed.seed_everything` instead.
  rank_zero_deprecation(
INFO:lightning_fabric.utilities.seed:Global seed set to 42
ChatGLMConfig {
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 20002,
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "initializer_weight": true,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 1,
  "pad_token_id": 20003,
  "position_encoding_2d": true,
  "precision": 16,
  "return_dict": false,
  "task_specific_params": {
    "learning_rate": 5e-05,
    "learning_rate_for_task": 5e-05
  },
  "torch_dtype": "float16",
  "transformers_version": "4.27.1",
  "use_cache": true,
  "vocab_size": 150528
}

TrainingArguments(optimizer='lion', scheduler_type='linear', scheduler=None, adv={'mode': None, 'emb_name=': 'embedding', 'attack_iters': 2, 'minibatch_replays': 2, 'alpha': 0.1, 'epsilon': 1.0}, hierarchical_position=None, learning_rate=5e-05, learning_rate_for_task=5e-05, max_epochs=20, max_steps=-1, optimizer_betas=(0.9, 0.999), adam_epsilon=1e-08, gradient_accumulation_steps=1, max_grad_norm=1.0, weight_decay=0, warmup_steps=0, train_batch_size=4, eval_batch_size=2, test_batch_size=2, seed=42)
ModelArguments(model_name_or_path='/root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/1b54948bb28de5258b55b893e193c3046a0b0484', model_type='chatglm', config_overrides=None, config_name='./config/config_small.json', tokenizer_name='/root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/1b54948bb28de5258b55b893e193c3046a0b0484', cache_dir=None, do_lower_case=False, use_fast_tokenizer=False, model_revision='main', use_auth_token=False)
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:26<00:00, 10.87s/it]
Traceback (most recent call last):
  File "infer.py", line 43, in <module>
    response, history = base_model.chat(tokenizer, "你好", history=[], max_length=1024)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1152, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/transformers/generation/utils.py", line 1452, in generate
    return self.sample(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/transformers/generation/utils.py", line 2468, in sample
    outputs = self(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 1072, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 920, in forward
    layer_ret = layer(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 601, in forward
    attention_outputs = self.attention(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 455, in forward
    context_layer, present, attention_probs = attention_fn(
  File "/root/miniconda3/envs/torch_1.13/lib/python3.8/site-packages/deep_training/nlp/models/chatglm/__init__.py", line 318, in attention_fn
    attention_probs = attention_probs.view(output_size[0] * output_size[1], output_size[2], -1)
AttributeError: 'str' object has no attribute 'view'

**Comment by ssbuild** [comment]
pip install -U deep_training >= 0.0.18 cpm_kernels icetk transformers>=4.26.1 deepspeed
try it

**Comment by Sniper970119** [comment]
hello I had `pip install -r requirements.txt' and check version in comment,but it still have some problems.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/30463691/226905619-c59c93af-604c-4bda-9301-dad4348a931b.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/30463691/226905751-e495c594-58be-4b49-9ca1-ea9e0f677464.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/30463691/226905818-29639112-c7fc-496f-8987-6160ba359fc8.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/30463691/226905860-4b96defc-7c85-46b6-88ce-42b48ca5c871.png">


<img width="716" alt="image" src="https://user-images.githubusercontent.com/30463691/226905939-54ee571d-dc33-45eb-9c69-35e3ad97108d.png">


> pip install -U deep_training >= 0.0.18 cpm_kernels icetk transformers>=4.26.1 deepspeed try it

**Comment by ssbuild** [comment]
你好 ,  0.0.20 已经更新同步pypi。
