### ISSUE TITLE
我这边更新了pip install -U deep_training >= 0.0.20，报错

### ISSUE THREAD

**Issue by bobo-wmdigit** [ssbuild/chatglm_finetuning#46]
ERROR: Could not find a version that satisfies the requirement 0.0.20 (from versions: none)
ERROR: No matching distribution found for 0.0.20

是不是有其他依赖环境啊？

**Comment by ssbuild** [comment]
可能国内还没同步，可以直接下载https://pypi.org/project/deep-training/#files

**Comment by bobo-wmdigit** [comment]
还是报错，我应该用你给的json，还是用[alpaca2qa.py](https://github.com/ssbuild/chatglm_finetuning/blob/main/alpaca2qa.py)脚本跑出来的数据？

**Comment by bobo-wmdigit** [comment]
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/nlp/pre_models/torch/chatglm/chatglm-6b'. Use `repo_type`
argument if needed. 我如果不改data_utils.py里的token名称，根本不能执行

**Comment by bobo-wmdigit** [comment]
我搞定了，能跑了，直接下官方的那个bin不行，要从头开始训练，我没用lora，现在的问题是，如果我开了fp16，就报：ValueError: Attempting to unscale FP16 gradients.这个错误，不开是能跑的

**Comment by qiangqiang-he** [comment]
你好，我也遇到了HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/nlp/pre_models/torch/chatglm/chatglm-6b'. Use repo_type
argument if needed这个问题，你改的data_utils.py的token的名称，请问具体是怎么改的呀

**Comment by ssbuild** [comment]
> 我搞定了，能跑了，直接下官方的那个bin不行，要从头开始训练，我没用lora，现在的问题是，如果我开了fp16，就报：ValueError: Attempting to unscale FP16 gradients.这个错误，不开是能跑的

可以尝试将config/config_small.json precision 改为32 ，然后修改 train.py Trainner 添加参数 precision=16 或者precision='bf16'

**Comment by bobo-wmdigit** [comment]
> 

你这个要引用"THUDM/chatglm-6b"，这个他就会自动取找了

**Comment by bobo-wmdigit** [comment]
> 你好，我也遇到了HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/nlp/pre_models/torch/chatglm/chatglm-6b'. Use repo_type argument if needed这个问题，你改的data_utils.py的token的名称，请问具体是怎么改的呀

你这个要引用"THUDM/chatglm-6b"，这个他就会自动取找了

**Comment by bobo-wmdigit** [comment]
> > 我搞定了，能跑了，直接下官方的那个bin不行，要从头开始训练，我没用lora，现在的问题是，如果我开了fp16，就报：ValueError: Attempting to unscale FP16 gradients.这个错误，不开是能跑的
> 
> 可以尝试将config/config_small.json precision 改为32 ，然后修改 train.py Trainner 添加参数 precision=16 或者precision='bf16'

我试一下最新版本，谢谢。
