### ISSUE TITLE
何时能支持多卡啊？

### ISSUE THREAD

**Issue by 460130107** [ssbuild/chatglm_finetuning#5]

**Comment by ssbuild** [comment]
easy , 修改 data_utils.py  train_info_args devices

**Comment by lyzKF** [comment]
@ssbuild 帅哥，为啥不进一步，支持一下deep speed训练呢

**Comment by lyzKF** [comment]
😁，多么善解人意的大佬



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月16日 00:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ssbuild/chatglm_finetuning] 何时能支持多卡啊？ (Issue #5) |

@lyzKF

just a strategy ， 已添加

**Comment by WaveLi123** [comment]
麻烦问下大佬deepspeed设置下训练过程中模型无法存储怎么解决？
 
![image](https://user-images.githubusercontent.com/10104047/225520645-94078a41-d3e2-4cc0-a8ab-5ca57c4de7f2.png)

**Comment by BestSongEver** [comment]
> 麻烦问下大佬deepspeed设置下训练过程中模型无法存储怎么解决？（一直停留在这里）
>  
> ![image](https://user-images.githubusercontent.com/10104047/225520645-94078a41-d3e2-4cc0-a8ab-5ca57c4de7f2.png)
> 

我也是这样

**Comment by sepilqi** [comment]
@BestSongEver @WaveLi123 你先临时 `rm -rf ./best_ckpt`
