### ISSUE TITLE
关于prompt 用的是‘响应’，又有‘输出’，略不一致的一点思考

### ISSUE THREAD

**Issue by Syno8** [ssbuild/chatglm_finetuning#50]
这里改成“编写适当的输出完成请求。” 之类会不会更好，感觉用的是响应，又是输出，略有不一致
从另一种角度考虑：模型有可能能理解到响应和输出的关系，作者如何看呢？

https://github.com/ssbuild/chatglm_finetuning/blob/bb74bc80f979ad81edf5bf5c01eb4756a5eaf4ad/alpaca2qa.py#L36

**Comment by ssbuild** [comment]
> 这里改成“编写适当的输出完成请求。” 之类会不会更好，感觉用的是响应，又是输出，略有不一致 从另一种角度考虑：模型有可能能理解到响应和输出的关系，作者如何看呢？
> 
> https://github.com/ssbuild/chatglm_finetuning/blob/bb74bc80f979ad81edf5bf5c01eb4756a5eaf4ad/alpaca2qa.py#L36

的确响应更合适，多谢指正。

**Comment by ssbuild** [comment]
感谢建议， 模板只是给大家一个参考，欢迎提交代码为开源共享

**Comment by wac81** [comment]
这个是alpaca翻译问题，其实影响不大。中英文的影响才大
