### ISSUE TITLE
关于alpaca2qa

### ISSUE THREAD

**Issue by BestSongEver** [ssbuild/chatglm_finetuning#52]
想请问，在alpaca2qa.py文件里：
"下面是一个指令,描述了一个任务,搭配一个输入,提供进一步的上下文。"，"编写适当完成请求的响应。\n\n"
或者
"下面是一个指令,描述了一个任务。"， "编写适当完成请求的响应。\n\n"
这两句看起来很长的prompt，是必要的吗，为什么不使用简短点的prompt，比如
“根据输入完成任务”、以及“完成以下任务”
@ssbuild 谢谢

**Comment by ssbuild** [comment]
当时job 只是把英文模板翻译过来，仅供借鉴 ，模板可以适当变换，哈哈。
