### ISSUE TITLE
EOFError: Ran out of input   这是什么错误？

### ISSUE THREAD

**Issue by zhangxiaoyuan1988** [ssbuild/chatglm_finetuning#55]
/data/z/zhangxiaoyuan/work/test/chatglm-fineturn/chatglm_finetuning/infer_finetuning.py:40 in    │
│ <module>                                                                                         │
│                                                                                                  │
│   37 │   if get_deepspeed_config() is None:                                                      │
│   38 │   │   train_weight = './best_ckpt/last-v3.ckpt'                                           │
│   39 │   │   assert os.path.exists(train_weight)                                                 │
│ ❱ 40 │   │   model = MyTransformer.load_from_checkpoint(train_weight, config=config,             │
│   41 │   │   │   │   │   │   │   │   │   │   │   │      model_args=model_args,                   │
│   42 │   │   │   │   │   │   │   │   │   │   │   │      training_args=training_args,             │
│   43 │   │   │   │   │   │   │   │   │   │   │   │      strict=False)                            │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/work/test/chatglm-fineturn/chatglm_finetuning/deep_training/nlp/models/tra │
│ nsformer.py:78 in load_from_checkpoint                                                           │
│                                                                                                  │
│    75 │   │   │   strict: bool = True,                                                           │
│    76 │   │   │   **kwargs: Any,                                                                 │
│    77 │   ) -> typing.Union["pl.LightningModule", "pl.LightningDataModule","MyLightningModule"   │
│ ❱  78 │   │   return super(MyLightningModule, cls).load_from_checkpoint(checkpoint_path,map_lo   │
│    79 │                                                                                          │
│    80 │   @property                                                                              │
│    81 │   def backbone(self):                                                                    │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/conda/envs/glm/lib/python3.8/site-packages/pytorch_lightning/core/saving.p │
│ y:139 in load_from_checkpoint                                                                    │
│                                                                                                  │
│   136 │   │   │   pretrained_model.freeze()                                                      │
│   137 │   │   │   y_hat = pretrained_model(x)                                                    │
│   138 │   │   """                                                                                │
│ ❱ 139 │   │   return _load_from_checkpoint(                                                      │
│   140 │   │   │   cls,                                                                           │
│   141 │   │   │   checkpoint_path,                                                               │
│   142 │   │   │   map_location,                                                                  │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/conda/envs/glm/lib/python3.8/site-packages/pytorch_lightning/core/saving.p │
│ y:160 in _load_from_checkpoint                                                                   │
│                                                                                                  │
│   157 │   if map_location is None:                                                               │
│   158 │   │   map_location = cast(_MAP_LOCATION_TYPE, lambda storage, loc: storage)              │
│   159 │   with pl_legacy_patch():                                                                │
│ ❱ 160 │   │   checkpoint = pl_load(checkpoint_path, map_location=map_location)                   │
│   161 │                                                                                          │
│   162 │   # convert legacy checkpoints to the new format                                         │
│   163 │   checkpoint = _pl_migrate_checkpoint(                                                   │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/conda/envs/glm/lib/python3.8/site-packages/lightning_fabric/utilities/clou │
│ d_io.py:48 in _load                                                                              │
│                                                                                                  │
│   45 │   │   )                                                                                   │
│   46 │   fs = get_filesystem(path_or_url)                                                        │
│   47 │   with fs.open(path_or_url, "rb") as f:                                                   │
│ ❱ 48 │   │   return torch.load(f, map_location=map_location)                                     │
│   49                                                                                             │
│   50                                                                                             │
│   51 def get_filesystem(path: _PATH, **kwargs: Any) -> AbstractFileSystem:                       │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/conda/envs/glm/lib/python3.8/site-packages/torch/serialization.py:815 in   │
│ load                                                                                             │
│                                                                                                  │
│    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │
│    813 │   │   │   except RuntimeError as e:                                                     │
│    814 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None           │
│ ❱  815 │   │   return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args  │
│    816                                                                                           │
│    817                                                                                           │
│    818 # Register pickling support for layout instances such as                                  │
│                                                                                                  │
│ /data/z/zhangxiaoyuan/conda/envs/glm/lib/python3.8/site-packages/torch/serialization.py:1033 in  │
│ _legacy_load                                                                                     │
│                                                                                                  │
│   1030 │   │   │   f"Received object of type \"{type(f)}\". Please update to Python 3.8.2 or ne  │
│   1031 │   │   │   "functionality.")                                                             │
│   1032 │                                                                                         │
│ ❱ 1033 │   magic_number = pickle_module.load(f, **pickle_load_args)                              │
│   1034 │   if magic_number != MAGIC_NUMBER:                                                      │
│   1035 │   │   raise RuntimeError("Invalid magic number; corrupt file?")                         │
│   1036 │   protocol_version = pickle_module.load(f, **pickle_load_args)                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
EOFError: Ran out of input

**Comment by zhangxiaoyuan1988** [comment]
谢谢回复，不过升级到3.8.16或原来的3.8.2，python3 infer_finetuning.py还是会有这个错误!

环境是
python 3.8.16
nvcc -V没有装cuda
Linux version 5.4.0-65-generic (buildd@lgw01-amd64-048) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu118.04)) https://github.com/TimDettmers/bitsandbytes/issues/7318.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm_finetuning/blob/f0259ee47acf7996d1da242d3fee3595b3ec08ff/infer.py#L42
如果没有GPU base_model.half().quantize(4).to(torch.device('cuda:0'))  修改为 base_model.float()

**Comment by zhangxiaoyuan1988** [comment]
1、python3 infer.py 可以执行了，不过在回答”晚上睡不着怎么办“之前出现了很多其他
2、python3  infer_finetuning.py  还是有这个问题

'''
...
 but 事业'中国人民银行

 but 同时还能做很多其他的事情，比如：

�

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but 事业'中国人民银行

 but
晚上睡不着应该怎么办   晚上睡不着可能会让你感到疲惫和不舒服，但以下是一些可以帮助你入睡的方法：

1. 建立一个规律的睡眠时间表：尽量在相同的时间上床和起床，即使在周末也要保持一致，帮助身体调节生物钟。

2. 创造一个舒适的睡眠环境：保持房间安静、凉爽、黑暗和舒适，有助于入睡。

3. 放松身心：尝试进行一些放松的活动，如深呼吸、冥想或渐进性肌肉松弛练习，减轻压力和焦虑，更容易入睡。

4. 避免使用电子设备：在睡觉前一个小时内避免使用电子设备，如手机、电脑和电视，因为屏幕的蓝光可能会干扰睡眠质量。

5. 避免饮食和饮料的刺激：在睡觉前几个小时避免饮用咖啡、茶和饮料等刺激性饮品，以及吃辛辣、油腻或难以消化的食物。

6. 练习一些放松的活动：进行一些放松的活动，如瑜伽或冥想，有助于缓解身体和心灵的紧张，更容易PROMPT 事业 中国人民银行 t=B_NORMAL_MAP&c=
 '''

**Comment by zhangxiaoyuan1988** [comment]
谢谢，可以了
