### ISSUE TITLE
数据有shuffle机制吗

### ISSUE THREAD

**Issue by lulia0228** [ssbuild/chatglm_finetuning#57]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/49608151/227193810-d0eab44a-2736-414c-b2a7-361b8f22bb39.png">
目前观察  每轮都是先loss低 然后增大,请教下这可能是什么原因？

**Comment by ssbuild** [comment]
> <img alt="image" width="349" src="https://user-images.githubusercontent.com/49608151/227193810-d0eab44a-2736-414c-b2a7-361b8f22bb39.png">
> 
> 目前观察 每轮都是先loss低 然后增大,请教下这可能是什么原因？

上传下全过程loss
