### ISSUE TITLE
训练模型的时候显存占用为什么会越来越大呢？

### ISSUE THREAD

**Issue by paperpplane** [ssbuild/chatglm_finetuning#6]
使用大概2000个数据训练6层，3个epoch，batch size4。初始显存占用是30G，后面大概每过100来个step，显存就会多占用4G，然后训着训着就cuda out of memory了

**Comment by ssbuild** [comment]
可能是前面对话短，后面对话数据长度较长 ， 导致OOM ， 可以适当减小max_length ， 如果减小长度解决请告诉我.

**Comment by paperpplane** [comment]
我设置的max_seq_length是1024，然后观察了一下，大概step到1000多的时候，显存的增加会停止

**Comment by paperpplane** [comment]
还想问一下，如果想全量训练的话要多少显存支持呢，目前是单卡46G八张卡，也无法支持全量训练吗

**Comment by ssbuild** [comment]
> 支

deepspeed stage 2 . 8张 a100可以微调

**Comment by WaveLi123** [comment]
> > 支
> 
> deepspeed stage 2 . 8张 a100可以微调

大佬，这里的a100是40G还是80G哈？
