### ISSUE TITLE
您好，请问infer_finetuning如何加载多卡的权重文件？

### ISSUE THREAD

**Issue by heyudage** [ssbuild/chatglm_finetuning#61]
您好，我通过多机多卡（6卡）进行微调，deepspeed stage3模式，num_layer 28，完成后生成的模型在checkpoint文件夹下，共计12个文件，可能是6卡形成的权重文件：
zero_pp_rank_【0至6】_mp_rank_00_model_states.pt（每个体积约217.6K）
zero_pp_rank_【0至6】_mp_rank_00_optim_states.pt（每个体积约7.8G）
infer_finetuning.py中提供两种方式加载权重，您默认为“直接加载权重”，加载12个模型中的任意模型报错。若改为“权重转换”后加载模型，模型中没有module，向您请教我该如何正确加载模型文件？

**Comment by heyudage** [comment]
通过“权重转换”方式生成并加载模型不会报错，但是模型任何无效果。 #51

**Comment by ssbuild** [comment]
感谢提出bug , #51 解决了deepspeed stage 0,1,2 权重加载 ， 目前已解决stage 0,1,2,3权重加载，请测试。

**Comment by heyudage** [comment]
您好，非常感谢您的回复！
stage3 新版的代码在运行load_from_checkpoint时会报错下图的错误，请问我应如何处理？
![CAPTURE_2023324_111027](https://user-images.githubusercontent.com/26505632/227415035-8d0971bf-6166-4ea3-aed4-0b586c5078db.jpg)

**Comment by ssbuild** [comment]
@heyudage 

感谢指出问题，已修复deepspeed stage 0,1,2,3 权重加载 ， 更新程序升级依赖后 ，重新训练即可，请测试。
