### ISSUE TITLE
训练完成大约总共要多久？

### ISSUE THREAD

**Issue by jiandam55** [ssbuild/chatglm_finetuning#63]
作者大侠，一轮训练结束后，收到如下日志，有点蒙，还要训练几轮？我这一轮花了37小时，训练完成大约总共要多久？
(git源码后的默认配置没动过)
......
Epoch 0: 100%|██████████| 637855/637855 [37:08:31<00:00,  4.77it/s, loss=nan, v_num=1]
Epoch 0: 100%|██████████| 637855/637855 [37:08:31<00:00,  4.77it/s, loss=nan, v_num=1]
Epoch 0:   0%|          | 0/637855 [00:00<?, ?it/s, loss=nan, v_num=1]                
Epoch 1:   0%|          | 0/637855 [00:00<?, ?it/s, loss=nan, v_num=1]
Epoch 1:   0%|          | 1/637855 [00:00<72:35:08,  2.44it/s, loss=nan, v_num=1]
Epoch 1:   0%|          | 1/637855 [00:00<79:52:50,  2.22it/s, loss=nan, v_num=1]
......

**Comment by linthy94** [comment]
你loss已经nan了，调一下训练参数吧。
想减少时间，要么增加batch_size，这需要有更大的显存；要么减少max_epochs

**Comment by jiandam55** [comment]
我是不是数据量也太大了，train.json有600多M

**Comment by ssbuild** [comment]
> 我是不是数据量也太大了，train.json有600多M

跟数据量没关系 ， 拉下新的代码 ， 制作数据训练，建议先用一部分数据调参，之后再大规模训练。
