### ISSUE TITLE
infer_lora_finetuning输出为空

### ISSUE THREAD

**Issue by Chtholly1** [ssbuild/chatglm_finetuning#68]
如下所示，lora训练完后，预测的结果为空，不知道问题出在哪，best_ckpt目录下也有adapter_config.json、adapter_model.bin、config.json三个文件鸭。
****************************** lora info
trainable params: 131072 || all params: 818081792 || trainable%: 0.016021869852348457
写一个诗歌，关于冬天   
晚上睡不着应该怎么办

**Comment by immortal5655** [comment]
我也有相似的问题

**Comment by AHNU** [comment]
请问必须全层才会有输出吗

**Comment by Chtholly1** [comment]
> 请问必须全层才会有输出吗

对，输出的时候要改成28层，原代码写的是1

**Comment by AHNU** [comment]
您发送的邮件已经收到，我会尽快给您答复！
