### ISSUE TITLE
记录下V100 16G训练参数

### ISSUE THREAD

**Issue by micrazy** [ssbuild/chatglm_finetuning#70]
资源有限，只有7*v100（16G）
尝试了很多办法，最终加入ZeRO-3-offload后可以跑起来了28层了：
deepspeed.json如下
`{
 "zero_allow_untested_optimizer": true,
 "zero_force_ds_cpu_optimizer": false,
  "fp16": {
    "enabled": true,
    "auto_cast": false,
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
   "zero_optimization": {
     "stage": 3,
     "allgather_partitions": true,
     "allgather_bucket_size": 5e8,
     "overlap_comm": false,
     "reduce_scatter": true,
     "reduce_bucket_size": 5e8,
     "contiguous_gradients" : true,
    "stage3_max_live_parameters" : 1e9,
    "stage3_max_reuse_distance" : 1e9,
    "stage3_prefetch_bucket_size" : 5e8,
    "stage3_param_persistence_threshold" : 1e6,
    "sub_group_size" : 1e12,
    "elastic_checkpoint" : true,
    "stage3_gather_16bit_weights_on_model_save": true,
    "ignore_unused_parameters": true,
    "round_robin_gradients": true,
    "offload_param": {
        "device": "cpu",
        "max_in_cpu": 1e9
    },
    "offload_optimizer": {
        "device": "cpu"
  }
 }
}`

其他参数：
layer_num 28
max_seq_length: 128
max_target_length: 100
train_batch 1

**Comment by ssbuild** [comment]
感谢提供dp3 配置，已支持deepspeed stage 0,1,2,3 权重 。

**Comment by luolanfeixue** [comment]
cpu内存多少？

**Comment by micrazy** [comment]
64C 512G

**Comment by robin087** [comment]
同为16GB V100，我在训练时，单轮对话可以正常训练，但是多轮对话还是会爆，请问您有出现过这种问题吗？

**Comment by micrazy** [comment]
可以看下OOM的时候，显存的碎片化情况，尝试调下max_split_size_mb参数
另外可以试下降低train_batch_size和max_seq_length
