### ISSUE TITLE
更新代码后遇到的问题：KeyError: 'attention_mask'

### ISSUE THREAD

**Issue by fourseven471** [ssbuild/chatglm_finetuning#72]
更新代码后，出现问题。
环境如下：
transformers==4.27.1
tokenizers==0.13.2
pytorch-lightning==1.9.4

错误如下：
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/48342616/227502812-ad7d5c3c-3697-497f-a3fa-94b4bd34b2ef.png">

**Comment by ssbuild** [comment]
需要删除output 缓存的record文件 ， 旧的缓存文件无法对标新的代码。

**Comment by LanShanPi** [comment]
@ssbuild 是删除日志文件还是什么。
