### ISSUE TITLE
推理时模型加载Killed了，有人遇到过吗，训练是没问题的

### ISSUE THREAD

**Issue by TccccD** [ssbuild/chatglm_finetuning#75]
![image](https://user-images.githubusercontent.com/14340567/227705919-c17dfbae-8b8d-43f8-8bb9-0bebcaecdc60.png)

**Comment by ssbuild** [comment]
确认下 推理机器，内存是否充足 ， 一般系统内存不足会killed程序

**Comment by TccccD** [comment]
> 

我用了v100 32g，和a100 80g都kill了

**Comment by TccccD** [comment]
看了下，是内存满了。。。infer_finetuning.py 先加载到内存的吗
