### ISSUE TITLE
代码更新运行报错

### ISSUE THREAD

**Issue by wtypty2** [ssbuild/chatglm_finetuning#76]
/home/wty/anaconda3/bin/python /media/wty/d/chatglm/glm/v10/train.py 
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpm315tex9
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpm315tex9/_remote_module_non_scriptable.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/wty/anaconda3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/wty/anaconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/wty/anaconda3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/wty/anaconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so...
INFO:pytorch_lightning.utilities.seed:Global seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:root:make_dataset ./data/alpaca-part-00.json train...
INFO:root:make data ./output/dataset_file_0_dupe_factor_0-train.record...
ChatGLMConfig {
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 20002,
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "initializer_weight": false,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 4,
  "pad_token_id": 20003,
  "position_encoding_2d": true,
  "precision": 16,
  "return_dict": false,
  "task_specific_params": {
    "learning_rate": 2e-05,
    "learning_rate_for_task": 2e-05
  },
  "torch_dtype": "float16",
  "transformers_version": "4.28.0.dev0",
  "use_cache": true,
  "vocab_size": 150528
}

INFO:root:load dataset to memory...
INFO:pytorch_lightning.utilities.seed:Global seed set to 42
INFO:pytorch_lightning.utilities.distributed:initializing deepspeed distributed: GLOBAL_RANK: 1, MEMBER: 2/2
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 1
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
WARNING:pytorch_lightning.loggers.tensorboard:Missing logger folder: output/lightning_logs
INFO:torch.distributed.distributed_c10d:Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
WARNING:pytorch_lightning.loggers.tensorboard:Missing logger folder: output/lightning_logs
/home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /media/wty/d/chatglm/glm/v10/best_ckpt exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
INFO:pytorch_lightning.utilities.rank_zero:Loading `train_dataloader` to estimate number of stepping batches.
/home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:219: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 40 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py:428: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/wty/d/chatglm/glm/v10/train.py:198 in <module>                        │
│                                                                              │
│   195 │   │   │   │   │   │   │   │   │   │   │   │   │   │   dataset_loader │
│   196 │   │                                                                  │
│   197 │   │   if train_datasets is not None:                                 │
│ ❱ 198 │   │   │   trainer.fit(model, train_dataloaders=train_datasets)       │
│   199 │                                                                      │
│   200 │   else:                                                              │
│   201 │   │   if not lora_args.with_lora:                                    │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:700 in fit                                                          │
│                                                                              │
│    697 │   │   │   datamodule: An instance of :class:`~pytorch_lightning.cor │
│    698 │   │   """                                                           │
│    699 │   │   self.strategy.model = model                                   │
│ ❱  700 │   │   self._call_and_handle_interrupt(                              │
│    701 │   │   │   self._fit_impl, model, train_dataloaders, val_dataloaders │
│    702 │   │   )                                                             │
│    703                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:652 in _call_and_handle_interrupt                                   │
│                                                                              │
│    649 │   │   """                                                           │
│    650 │   │   try:                                                          │
│    651 │   │   │   if self.strategy.launcher is not None:                    │
│ ❱  652 │   │   │   │   return self.strategy.launcher.launch(trainer_fn, *arg │
│    653 │   │   │   else:                                                     │
│    654 │   │   │   │   return trainer_fn(*args, **kwargs)                    │
│    655 │   │   # TODO(awaelchli): Unify both exceptions below, where `Keyboa │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/strategies │
│ /launchers/subprocess_script.py:93 in launch                                 │
│                                                                              │
│    90 │   │   """                                                            │
│    91 │   │   if not self.cluster_environment.creates_processes_externally:  │
│    92 │   │   │   self._call_children_scripts()                              │
│ ❱  93 │   │   return function(*args, **kwargs)                               │
│    94 │                                                                      │
│    95 │   def _call_children_scripts(self) -> None:                          │
│    96 │   │   # bookkeeping of spawned processes                             │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:741 in _fit_impl                                                    │
│                                                                              │
│    738 │   │   self._ckpt_path = self.__set_ckpt_path(                       │
│    739 │   │   │   ckpt_path, model_provided=True, model_connected=self.ligh │
│    740 │   │   )                                                             │
│ ❱  741 │   │   results = self._run(model, ckpt_path=self.ckpt_path)          │
│    742 │   │                                                                 │
│    743 │   │   assert self.state.stopped                                     │
│    744 │   │   self.training = False                                         │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1104 in _run                                                        │
│                                                                              │
│   1101 │   │   self.strategy.setup_environment()                             │
│   1102 │   │   self.__setup_profiler()                                       │
│   1103 │   │                                                                 │
│ ❱ 1104 │   │   self._call_setup_hook()  # allow user to setup lightning_modu │
│   1105 │   │                                                                 │
│   1106 │   │   # check if we should delay restoring checkpoint till later    │
│   1107 │   │   if not self.strategy.restore_checkpoint_after_setup:          │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1448 in _call_setup_hook                                            │
│                                                                              │
│   1445 │   │   if self.datamodule is not None:                               │
│   1446 │   │   │   self._call_lightning_datamodule_hook("setup", stage=fn)   │
│   1447 │   │   self._call_callback_hooks("setup", stage=fn)                  │
│ ❱ 1448 │   │   self._call_lightning_module_hook("setup", stage=fn)           │
│   1449 │   │                                                                 │
│   1450 │   │   self.strategy.barrier("post_setup")                           │
│   1451                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1549 in _call_lightning_module_hook                                 │
│                                                                              │
│   1546 │   │   pl_module._current_fx_name = hook_name                        │
│   1547 │   │                                                                 │
│   1548 │   │   with self.profiler.profile(f"[LightningModule]{pl_module.__cl │
│ ❱ 1549 │   │   │   output = fn(*args, **kwargs)                              │
│   1550 │   │                                                                 │
│   1551 │   │   # restore current_fx when nested context                      │
│   1552 │   │   pl_module._current_fx_name = prev_fx_name                     │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/deep_training/nlp/models/tra │
│ nsformer.py:396 in setup                                                     │
│                                                                              │
│   393 │                                                                      │
│   394 │   def setup(self, stage: str) -> None:                               │
│   395 │   │   setattr(self.backbone, 'trainer', self.trainer)                │
│ ❱ 396 │   │   setattr(self.backbone, 'estimated_stepping_batches', self.trai │
│   397 │                                                                      │
│   398 │                                                                      │
│   399 │   def get_named_parameters(self):                                    │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:2771 in estimated_stepping_batches                                  │
│                                                                              │
│   2768 │   │                                                                 │
│   2769 │   │   if self.train_dataloader is None:                             │
│   2770 │   │   │   rank_zero_info("Loading `train_dataloader` to estimate nu │
│ ❱ 2771 │   │   │   self.reset_train_dataloader()                             │
│   2772 │   │                                                                 │
│   2773 │   │   total_batches = self.num_training_batches                     │
│   2774                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1848 in reset_train_dataloader                                      │
│                                                                              │
│   1845 │   │   module = model or self.lightning_module or self.datamodule    │
│   1846 │   │   orig_train_batches = self.num_training_batches = (            │
│   1847 │   │   │   len(self.train_dataloader)                                │
│ ❱ 1848 │   │   │   if has_len_all_ranks(self.train_dataloader, self.strategy │
│   1849 │   │   │   else float("inf")                                         │
│   1850 │   │   )                                                             │
│   1851 │   │   if orig_train_batches == 0:                                   │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ data.py:138 in has_len_all_ranks                                             │
│                                                                              │
│   135 │   infinite dataloader."""                                            │
│   136 │   try:                                                               │
│   137 │   │   local_length = len(dataloader)                                 │
│ ❱ 138 │   │   total_length = training_type.reduce(torch.tensor(local_length) │
│   139 │   │                                                                  │
│   140 │   │   if total_length == 0:                                          │
│   141 │   │   │   rank_zero_warn(                                            │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/strategies │
│ /ddp.py:344 in reduce                                                        │
│                                                                              │
│   341 │   │   │   reduced value, except when the input was not a tensor the  │
│   342 │   │   """                                                            │
│   343 │   │   if isinstance(tensor, Tensor):                                 │
│ ❱ 344 │   │   │   tensor = sync_ddp_if_available(tensor, group, reduce_op=re │
│   345 │   │   return tensor                                                  │
│   346 │                                                                      │
│   347 │   def training_step(self, *args, **kwargs) -> STEP_OUTPUT:           │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ distributed.py:127 in sync_ddp_if_available                                  │
│                                                                              │
│   124 │   │   reduced value                                                  │
│   125 │   """                                                                │
│   126 │   if distributed_available():                                        │
│ ❱ 127 │   │   return sync_ddp(result, group=group, reduce_op=reduce_op)      │
│   128 │   return result                                                      │
│   129                                                                        │
│   130                                                                        │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ distributed.py:168 in sync_ddp                                               │
│                                                                              │
│   165 │                                                                      │
│   166 │   # sync all processes before reduction                              │
│   167 │   torch.distributed.barrier(group=group)                             │
│ ❱ 168 │   torch.distributed.all_reduce(result, op=op, group=group, async_op= │
│   169 │                                                                      │
│   170 │   if divide_by_world_size:                                           │
│   171 │   │   result = result / torch.distributed.get_world_size(group)      │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/torch/distributed/distribute │
│ d_c10d.py:1536 in all_reduce                                                 │
│                                                                              │
│   1533 │   │   default_pg = _get_default_group()                             │
│   1534 │   │   work = default_pg.allreduce([tensor], opts)                   │
│   1535 │   else:                                                             │
│ ❱ 1536 │   │   work = group.allreduce([tensor], opts)                        │
│   1537 │                                                                     │
│   1538 │   if async_op:                                                      │
│   1539 │   │   return work                                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Tensors must be CUDA and dense
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/wty/d/chatglm/glm/v10/train.py:198 in <module>                        │
│                                                                              │
│   195 │   │   │   │   │   │   │   │   │   │   │   │   │   │   dataset_loader │
│   196 │   │                                                                  │
│   197 │   │   if train_datasets is not None:                                 │
│ ❱ 198 │   │   │   trainer.fit(model, train_dataloaders=train_datasets)       │
│   199 │                                                                      │
│   200 │   else:                                                              │
│   201 │   │   if not lora_args.with_lora:                                    │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:700 in fit                                                          │
│                                                                              │
│    697 │   │   │   datamodule: An instance of :class:`~pytorch_lightning.cor │
│    698 │   │   """                                                           │
│    699 │   │   self.strategy.model = model                                   │
│ ❱  700 │   │   self._call_and_handle_interrupt(                              │
│    701 │   │   │   self._fit_impl, model, train_dataloaders, val_dataloaders │
│    702 │   │   )                                                             │
│    703                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:654 in _call_and_handle_interrupt                                   │
│                                                                              │
│    651 │   │   │   if self.strategy.launcher is not None:                    │
│    652 │   │   │   │   return self.strategy.launcher.launch(trainer_fn, *arg │
│    653 │   │   │   else:                                                     │
│ ❱  654 │   │   │   │   return trainer_fn(*args, **kwargs)                    │
│    655 │   │   # TODO(awaelchli): Unify both exceptions below, where `Keyboa │
│    656 │   │   except KeyboardInterrupt as exception:                        │
│    657 │   │   │   rank_zero_warn("Detected KeyboardInterrupt, attempting gr │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:741 in _fit_impl                                                    │
│                                                                              │
│    738 │   │   self._ckpt_path = self.__set_ckpt_path(                       │
│    739 │   │   │   ckpt_path, model_provided=True, model_connected=self.ligh │
│    740 │   │   )                                                             │
│ ❱  741 │   │   results = self._run(model, ckpt_path=self.ckpt_path)          │
│    742 │   │                                                                 │
│    743 │   │   assert self.state.stopped                                     │
│    744 │   │   self.training = False                                         │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1104 in _run                                                        │
│                                                                              │
│   1101 │   │   self.strategy.setup_environment()                             │
│   1102 │   │   self.__setup_profiler()                                       │
│   1103 │   │                                                                 │
│ ❱ 1104 │   │   self._call_setup_hook()  # allow user to setup lightning_modu │
│   1105 │   │                                                                 │
│   1106 │   │   # check if we should delay restoring checkpoint till later    │
│   1107 │   │   if not self.strategy.restore_checkpoint_after_setup:          │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1448 in _call_setup_hook                                            │
│                                                                              │
│   1445 │   │   if self.datamodule is not None:                               │
│   1446 │   │   │   self._call_lightning_datamodule_hook("setup", stage=fn)   │
│   1447 │   │   self._call_callback_hooks("setup", stage=fn)                  │
│ ❱ 1448 │   │   self._call_lightning_module_hook("setup", stage=fn)           │
│   1449 │   │                                                                 │
│   1450 │   │   self.strategy.barrier("post_setup")                           │
│   1451                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1549 in _call_lightning_module_hook                                 │
│                                                                              │
│   1546 │   │   pl_module._current_fx_name = hook_name                        │
│   1547 │   │                                                                 │
│   1548 │   │   with self.profiler.profile(f"[LightningModule]{pl_module.__cl │
│ ❱ 1549 │   │   │   output = fn(*args, **kwargs)                              │
│   1550 │   │                                                                 │
│   1551 │   │   # restore current_fx when nested context                      │
│   1552 │   │   pl_module._current_fx_name = prev_fx_name                     │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/deep_training/nlp/models/tra │
│ nsformer.py:396 in setup                                                     │
│                                                                              │
│   393 │                                                                      │
│   394 │   def setup(self, stage: str) -> None:                               │
│   395 │   │   setattr(self.backbone, 'trainer', self.trainer)                │
│ ❱ 396 │   │   setattr(self.backbone, 'estimated_stepping_batches', self.trai │
│   397 │                                                                      │
│   398 │                                                                      │
│   399 │   def get_named_parameters(self):                                    │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:2771 in estimated_stepping_batches                                  │
│                                                                              │
│   2768 │   │                                                                 │
│   2769 │   │   if self.train_dataloader is None:                             │
│   2770 │   │   │   rank_zero_info("Loading `train_dataloader` to estimate nu │
│ ❱ 2771 │   │   │   self.reset_train_dataloader()                             │
│   2772 │   │                                                                 │
│   2773 │   │   total_batches = self.num_training_batches                     │
│   2774                                                                       │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/tr │
│ ainer.py:1848 in reset_train_dataloader                                      │
│                                                                              │
│   1845 │   │   module = model or self.lightning_module or self.datamodule    │
│   1846 │   │   orig_train_batches = self.num_training_batches = (            │
│   1847 │   │   │   len(self.train_dataloader)                                │
│ ❱ 1848 │   │   │   if has_len_all_ranks(self.train_dataloader, self.strategy │
│   1849 │   │   │   else float("inf")                                         │
│   1850 │   │   )                                                             │
│   1851 │   │   if orig_train_batches == 0:                                   │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ data.py:138 in has_len_all_ranks                                             │
│                                                                              │
│   135 │   infinite dataloader."""                                            │
│   136 │   try:                                                               │
│   137 │   │   local_length = len(dataloader)                                 │
│ ❱ 138 │   │   total_length = training_type.reduce(torch.tensor(local_length) │
│   139 │   │                                                                  │
│   140 │   │   if total_length == 0:                                          │
│   141 │   │   │   rank_zero_warn(                                            │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/strategies │
│ /ddp.py:344 in reduce                                                        │
│                                                                              │
│   341 │   │   │   reduced value, except when the input was not a tensor the  │
│   342 │   │   """                                                            │
│   343 │   │   if isinstance(tensor, Tensor):                                 │
│ ❱ 344 │   │   │   tensor = sync_ddp_if_available(tensor, group, reduce_op=re │
│   345 │   │   return tensor                                                  │
│   346 │                                                                      │
│   347 │   def training_step(self, *args, **kwargs) -> STEP_OUTPUT:           │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ distributed.py:127 in sync_ddp_if_available                                  │
│                                                                              │
│   124 │   │   reduced value                                                  │
│   125 │   """                                                                │
│   126 │   if distributed_available():                                        │
│ ❱ 127 │   │   return sync_ddp(result, group=group, reduce_op=reduce_op)      │
│   128 │   return result                                                      │
│   129                                                                        │
│   130                                                                        │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/pytorch_lightning/utilities/ │
│ distributed.py:168 in sync_ddp                                               │
│                                                                              │
│   165 │                                                                      │
│   166 │   # sync all processes before reduction                              │
│   167 │   torch.distributed.barrier(group=group)                             │
│ ❱ 168 │   torch.distributed.all_reduce(result, op=op, group=group, async_op= │
│   169 │                                                                      │
│   170 │   if divide_by_world_size:                                           │
│   171 │   │   result = result / torch.distributed.get_world_size(group)      │
│                                                                              │
│ /home/wty/anaconda3/lib/python3.9/site-packages/torch/distributed/distribute │
│ d_c10d.py:1536 in all_reduce                                                 │
│                                                                              │
│   1533 │   │   default_pg = _get_default_group()                             │
│   1534 │   │   work = default_pg.allreduce([tensor], opts)                   │
│   1535 │   else:                                                             │
│ ❱ 1536 │   │   work = group.allreduce([tensor], opts)                        │
│   1537 │                                                                     │
│   1538 │   if async_op:                                                      │
│   1539 │   │   return work                                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Tensors must be CUDA and dense

Process finished with exit code 1

**Comment by wtypty2** [comment]
设置为train_info_args = {
    'devices': 2,
    'data_backend': 'record',
    'model_type': 'chatglm',
    # 预训练模型路径 , 从0训练，则置空
    'model_name_or_path': 'THUDM/chatglm-6b',
    'config_name': './config/config.json',
    'tokenizer_name': 'THUDM/chatglm-6b',
    'convert_onnx': False, # 转换onnx模型
    'do_train': True,
    'train_file':  [ './data/alpaca-part-00.json'],
    'max_epochs': 5,
    'max_steps': -1,
    'optimizer': 'lion', # one of adamw,adam,lamb,lion
    'scheduler_type': 'linear',
    'optimizer_betas': (0.9, 0.999),
    'train_batch_size': 4,
    'eval_batch_size': 2,
    'test_batch_size': 2,
    'learning_rate': 2e-5,  #
    'adam_epsilon': 1e-8,
    'gradient_accumulation_steps': 1,
    'max_grad_norm': 1.0,
    'weight_decay': 0,
    'warmup_steps': 0,
    'output_dir': './output',
    'max_seq_length': 1024, # 如果资源充足，推荐长度2048 与官方保持一致
    'max_target_length': 100,  # 预测最大长度, 保留字段
    'use_fast_tokenizer': False,
    'do_lower_case': False,

    ##############  lora模块
    'with_lora': False,  # 是否启用lora模块
    'inference_mode': False, # 推理模型, 不需要手动设置
    'r': 8,
    'target_modules': ['query_key_value'],
    'target_dtype': '16',
    'lora_alpha': 32,
    # 'enable_lora': [True],
    'enable_lora': None,
    'lora_dropout': 0.1,
    'bias': 'none',  # Bias type for Lora. Can be 'none', 'all' or 'lora_only'"
}

#lora 模式暂时不支持deepspeed
enable_deepspeed = True
#################################################################################
deepspeed.json
{
 "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": false,
    "auto_cast": false,
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
   "zero_optimization": {
     "stage": 2,
     "allgather_partitions": true,
     "allgather_bucket_size": 5e8,
     "overlap_comm": false,
     "reduce_scatter": true,
     "reduce_bucket_size": 5e8,
     "contiguous_gradients" : true,

    "stage3_max_live_parameters" : 1e9,
    "stage3_max_reuse_distance" : 1e9,
    "stage3_prefetch_bucket_size" : 5e8,
    "stage3_param_persistence_threshold" : 1e6,
    "sub_group_size" : 1e12,
    "elastic_checkpoint" : true,
    "stage3_gather_16bit_weights_on_model_save": true,
    "ignore_unused_parameters": true,
    "round_robin_gradients": true
    }
}
######################################################################################
config.json
{
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 150004,
  "eos_token_id": 150005,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 4,
  "position_encoding_2d": true,
  "torch_dtype": "float16",
  "transformers_version": "4.23.1",
  "use_cache": true,
  "vocab_size": 150528,
  "precision": 16
}

**Comment by ssbuild** [comment]
删除旧的output 缓存record 文件 ，制作数据 ,训练  try it.
