### ISSUE TITLE
finetuning好了，但是推理的时候只出现空的或者符号

### ISSUE THREAD

**Issue by TccccD** [ssbuild/chatglm_finetuning#79]
![image](https://user-images.githubusercontent.com/14340567/227722138-c6e15381-dc85-4684-8a7f-50cba3f8cf98.png)

用的是28层的，finetuning了5个epochs。

**Comment by ssbuild** [comment]
欠拟合

**Comment by paulcx** [comment]
我也遇到这个问题，感觉应该不是这个问题。照理说finetuning就是训练几步也应该有输出，毕竟对模型权重的更新没那么大。

**Comment by TccccD** [comment]
> 我也遇到这个问题，感觉应该不是这个问题。照理说finetuning就是训练几步也应该有输出，毕竟对模型权重的更新没那么大。

@paulcx 我也是你这个疑问，@ssbuild 用的默认的lion，学习率是2e-5，看了下训练loss，发现第一个epoch loss正常下降到2.5，后面几个epoch突然涨到了6。试了下，如果换成adamw，loss直接nan了。

**Comment by paulcx** [comment]
一个排查的思路是看下训练过程中从输入到损失过程中的数值分析看看是否正常，还有就是推理阶段输出的数值。自觉是感觉哪里不太对。

**Comment by ssbuild** [comment]
如果question很长会出现Loss nan , 增加了三种数据策略，欢迎测试指正~

**Comment by moyu505** [comment]
数据预处理黄行符号的问题，去掉换行符号

**Comment by paulcx** [comment]
> 数据预处理黄行符号的问题，去掉换行符号

哪里的数据预处理？

**Comment by moyu505** [comment]
> > 数据预处理黄行符号的问题，去掉换行符号
> 
> 哪里的数据预处理？

paragraph = [(preprocess(session['q']),preprocess('\n'.join(session['a']))) for session in paragraph]

**Comment by SizhaoXu** [comment]
您好，这个输出为空的情况您解决了吗？我具体也碰到了，with_lora启动train.py后，调用infer_lora_finetuning.py输出为空，改了参数还是为空

**Comment by moyu505** [comment]
> > > 数据预处理黄行符号的问题，去掉换行符号
> > 
> > 
> > 哪里的数据预处理？
> 
> paragraph = [(preprocess(session['q']),preprocess('\n'.join(session['a']))) for session in paragraph]

修改这个换行，是没开启lora的这个参数的，可以生效；我开启lora参数后，跑28层，loss是nan，预测也为空

**Comment by moyu505** [comment]
> 

数据2000个吧，效果很差，也在找原因

**Comment by paulcx** [comment]
> > > 数据预处理黄行符号的问题，去掉换行符号
> > 
> > 
> > 哪里的数据预处理？
> 
> paragraph = [(preprocess(session['q']),preprocess('\n'.join(session['a']))) for session in paragraph]

推理的时候没有用到预处理吧，这个只是在制作训练数据集的时候才调用？

**Comment by nieallen** [comment]
> > 我也遇到这个问题，感觉应该不是这个问题。照理说finetuning就是训练几步也应该有输出，毕竟对模型权重的更新没那么大。
> 
> @paulcx 我也是你这个疑问，@ssbuild 用的默认的lion，学习率是2e-5，看了下训练loss，发现第一个epoch loss正常下降到2.5，后面几个epoch突然涨到了6。试了下，如果换成adamw，loss直接nan了。

我也是这个问题，生成为空，我是4400个多轮对话数据。loss的问题也和你一样，请问你解决了吗

**Comment by wudi001007** [comment]
我也遇到同样问题。 加载了15层 开了lora，可训练参数2M，数据量8万左右，全部是单论对话。  ft结果很多重复生成的token，或者是符号。  loss 最小6左右。 不知道是不是 数据量太大 可训练参数比较小 欠拟合。

**Comment by paulcx** [comment]
不能说解决了吧，换了几个不同的推理模板，主要是用制作训练集的那个。效果好一些，在一些指令上仍然会出现乱输出等情况。不过看到大家都遇到这个问题，我也就安心了，我不是一个人😂

**Comment by MichaelToLearn** [comment]
> > > 数据预处理黄行符号的问题，去掉换行符号
> > 
> > 
> > 哪里的数据预处理？
> 
> paragraph = [(preprocess(session['q']),preprocess('\n'.join(session['a']))) for session in paragraph]

难道是数据集中不能包含符号吗？比如字面量的 \n 或者其他的代码符号等？
