### ISSUE TITLE
loss不收敛的问题

### ISSUE THREAD

**Issue by weizhenzhao** [ssbuild/chatglm_finetuning#80]
![loss](https://user-images.githubusercontent.com/13706689/227749173-00dafe8b-2457-4044-b4b6-b63c4b512f62.png)
![6 3B](https://user-images.githubusercontent.com/13706689/227749304-ba0a4edd-bf31-485d-afe5-223f3a46dfc2.png)

- @ssbuild大佬，您好，我用2张48G的A40，训练了28层+deepspeed 3，目前跑了不到1个epoch，20%的数据总数据11000多条
- 但是看loss曲线，不太像是有能收敛的样子，想问下是这loss本来就不收敛吗？
- 之前我跑过lora模式的28层，loss也是不收敛，是不是代码哪里有些问题呀？
- 我跑过小批量数据几十条的那种loss是收敛的，但是数据量一多loss它就不收敛了，是不是数据拼接或者模型保存的哪里有问题？

Thanks
weizhen

**Comment by ssbuild** [comment]
确认下代码是否是新的 ，不知道是不是之前的bug版本。

**Comment by weizhenzhao** [comment]
是最新的版本
![lora](https://user-images.githubusercontent.com/13706689/227759031-56c12514-3113-4781-9188-77751da6f3d3.png)

- 我还跑了一个版本的lora，28层，lion优化器，学习率2e-5。
- 看起来loss就在前几个step会下降，之后就一直震荡，然后就不下降了。

**Comment by ssbuild** [comment]
可能你的数据 ，在大模型上面拟合的快， 训练完成之后看看效果吧。

**Comment by ssbuild** [comment]
多调参实验， 然后看看效果

**Comment by weizhenzhao** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/13706689/227761943-d396fc59-821f-468a-9c67-b002ee32c2a5.png">

@ssbuild
想问下，您训练的时候，loss都会下降得很快吗？我每次训练不论用什么样的数据集，在lora模式下，然后loss都下降得很快。
就800多个epoch 然后loss就从8点几  下降到了 2点几。

**Comment by weizhenzhao** [comment]
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/13706689/227762581-4b7bded3-b32e-4580-b3c5-6d8b0bccfb84.png">

- 因为我的训练数据集里面有一些比较重复的，打招呼的信息，我在想需不需要删掉这些。
- 然后从第二轮开始训练？

**Comment by weizhenzhao** [comment]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/13706689/227778696-e5ca3df1-882b-485c-abf2-43e65a3faccf.png">
又训练了一个版本，把数据量增大到了23000条，还是不收敛。
@ssbuild 
我在想，刚看过您写的deep_training包中，PretrainGLMModel那个类，
1、会不会是mask的方式有问题，感觉清华那个GLM模型用的也是传统的GPT2 的Transformer Decoder。
     区别就是mask attention矩阵的构造长得不一样。
2、还有一点就是loss的计算方式的，我看您用的是 错一位然后去计算交叉熵，这是GPT2中的做法。
    会不会清华那个GLM预训练的时候，把loss给修改了一下，然后才导致目前微调的时候不收敛的呀？

只是提两点可能的情况。

Thanks
weizhen

**Comment by ssbuild** [comment]
看你的数据属实简单，拟合可能较快 ， 单凭这个无法得出结论，我的建议你切换数据，调参训练。

**Comment by weizhenzhao** [comment]
我跑过好几遍了，数据集也换过好几份了。真的不收敛。

**Comment by ssbuild** [comment]
> 我跑过好几遍了，数据集也换过好几份了。真的不收敛。

切换数据集需要删除缓存 output 下的 record 文件 。

**Comment by weizhenzhao** [comment]
删除了

**Comment by weizhenzhao** [comment]
我试过在几百条的情况下是收敛的，但是数据量一旦增加到几万条，它就一直波动，不下降了。

**Comment by ssbuild** [comment]
总结下前期收敛很快 ，后期趋于稳定 ，然后小范围震荡 ， 这个应该也是预训练模型训练比较充分的表现。  
however 先记录下您这个问题 , 持续跟踪中 。

**Comment by paulcx** [comment]
@ssbuild 有个问题想问下，在制作数据集的时候用了提示模板：
```
PROMPT_DICT = {
    "prompt_input": (
        "下面是一个指令,描述了一个任务,搭配一个输入,提供进一步的上下文。"
        "编写适当的输出完成请求。\n\n"
        "### 指令:\n{instruction}\n\n### 请求:\n{input}\n\n### 响应:"
    ),
    "prompt_no_input": (
        "下面是一个指令,描述了一个任务。"
        "编写适当的输出完成请求。\n\n"
        "### 指令:\n{instruction}\n\n### 响应:"
    ),
}
```
在推理阶段是否也需要用相应模板？目前的代码是：
```
    response, history = base_model.chat(tokenizer, "写一个诗歌，关于冬天", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=0.7, temperature=0.95,)
    print('写一个诗歌，关于冬天',' ',response)

    response, history = base_model.chat(tokenizer, "晚上睡不着应该怎么办", history=[],max_length=2048,
                                        eos_token_id=config.eos_token_id,
                                        do_sample=True, top_p=0.7, temperature=0.95,)
    print('晚上睡不着应该怎么办',' ',response)
```

**Comment by ssbuild** [comment]
> response, history = base_model.chat(tokenizer, "写一个诗歌，关于冬天", history=[],max_length=2048,
>                                         eos_token_id=config.eos_token_id,
>                                         do_sample=True, top_p=0.7, temperature=0.95,)
>     print('写一个诗歌，关于冬天',' ',response)
> 
>     response, history = base_model.chat(tokenizer, "晚上睡不着应该怎么办", history=[],max_length=2048,
>                                         eos_token_id=config.eos_token_id,
>                                         do_sample=True, top_p=0.7, temperature=0.95,)
>     print('晚上睡不着应该怎么办',' ',response)

可以适当调整  ，  prompt 也可以 改成 “{question}\n\n### 响应:”  ，  做实验验证下 , try it.

**Comment by paulcx** [comment]
> > response, history = base_model.chat(tokenizer, "写一个诗歌，关于冬天", history=[],max_length=2048,
> > eos_token_id=config.eos_token_id,
> > do_sample=True, top_p=0.7, temperature=0.95,)
> > print('写一个诗歌，关于冬天',' ',response)
> > ```
> > response, history = base_model.chat(tokenizer, "晚上睡不着应该怎么办", history=[],max_length=2048,
> >                                     eos_token_id=config.eos_token_id,
> >                                     do_sample=True, top_p=0.7, temperature=0.95,)
> > print('晚上睡不着应该怎么办',' ',response)
> > ```
> 
> 可以适当调整 ， prompt 也可以 改成 “{question}\n\n### 响应:” ， 做实验验证下 , try it.

做了对比试验，确实比不加要好，感觉在微调方面更进一步了，现在还有一些细节可能需要更精细的实验。有没有群可以加一个的。

**Comment by ssbuild** [comment]
> > > response, history = base_model.chat(tokenizer, "写一个诗歌，关于冬天", history=[],max_length=2048,
> > > eos_token_id=config.eos_token_id,
> > > do_sample=True, top_p=0.7, temperature=0.95,)
> > > print('写一个诗歌，关于冬天',' ',response)
> > > ```
> > > response, history = base_model.chat(tokenizer, "晚上睡不着应该怎么办", history=[],max_length=2048,
> > >                                     eos_token_id=config.eos_token_id,
> > >                                     do_sample=True, top_p=0.7, temperature=0.95,)
> > > print('晚上睡不着应该怎么办',' ',response)
> > > ```
> > 
> > 
> > 可以适当调整 ， prompt 也可以 改成 “{question}\n\n### 响应:” ， 做实验验证下 , try it.
> 
> 做了对比试验，确实比不加要好，感觉在微调方面更进一步了，现在还有一些细节可能需要更精细的实验。有没有群可以加一个的。

qq group 185144988

**Comment by weizhenzhao** [comment]
@ssbuild 
请问文本输入的时候，是在文本哪里添加的  MASK , 和gMask 的special token呀？
好像在代码里面没找到呢。

**Comment by weizhenzhao** [comment]
@ssbuild 
大佬能加个微信或者QQ仔细探讨一下嘛？

**Comment by weizhenzhao** [comment]
@ssbuild 
大佬。fix tokenizer.eos_token_id != config.eos_token_id bug
自从昨晚这个bug修复之后，我发现loss居然已经开始收敛了。

![image](https://user-images.githubusercontent.com/13706689/228108472-24a22dd9-6bc7-4655-9ab0-d4204cdd72de.png)

- 这张是1层的，半经度，用的lora模式。收敛得很稳定。7万条数据

<img width="924" alt="image" src="https://user-images.githubusercontent.com/13706689/228108359-d62ca27a-95fc-4984-82b6-beb1dfa30a5f.png">

- 上面这个是22层的。半经度用的lora模式，后面loss降到2左右会震荡，
- 我以为是半精度，表示小时位数不够，更深层的网络权重会比较小，半精度cover不了，所以会一直震荡。
- 感觉可以close掉了。

**Comment by ssbuild** [comment]
ok ,  it is so surprised

**Comment by cristianohello** [comment]
@weizhenzhao 

大佬您好。

fix tokenizer.eos_token_id != config.eos_token_id bug
自从昨晚这个bug修复之后，这个指的是哪里的代码修改了？
能详细说说怎么改的吗？

**Comment by weizhenzhao** [comment]
@cristianohello 

请参考这个fix
https://github.com/ssbuild/chatglm_finetuning/commit/b625c3986e536da77abeea274d9e4f94448dce50

**Comment by cristianohello** [comment]
@weizhenzhao 你好，谢谢大佬。
有个问题想请教您一下，我的多轮对话数据集是领域的，我看了你的是闲聊多轮对话。咱们的数据集格式是一样的。
我的情况是loss就在前几个step会下降，之后就一直震荡，然后就不下降了。
数据集有1万条，我在想是不是数据集不能有空格和特殊符号、以及表情符号的原因。或者说，数据集的回复a键不能为空，比如：{"q":"该问题已关闭，您无法继续回复，如未填写问诊报告请尽快填写，无问诊报告将无法结算收益","a":[]}，这个就是空回复对话。

![eacvTyegjq](https://user-images.githubusercontent.com/109277248/229330527-d93062de-c99c-4ee3-9105-9406bd51b76d.jpg)

**Comment by cristianohello** [comment]
@weizhenzhao 能加个联系方式吗？大佬，感谢感谢
QQ：1240368588

**Comment by weizhenzhao** [comment]
如果用的lion 优化器 学习率改成 2e-6 作者大佬默认的2e-5。
实测如果是28层的话 学习率要改得小一点。

**Comment by ssbuild** [comment]
a键值不允许空 。

**Comment by cristianohello** [comment]
@weizhenzhao 好的，谢谢指导，我试验一下

**Comment by cristianohello** [comment]
@ssbuild 好的，谢谢指导。
a的值不能为空，明白。那么q的值能为空吗？
比如：
{"q":"","a":[车打不了火可以多打几次，有问题随时问我。]}
像这个例子，q为空可以吧？

**Comment by cristianohello** [comment]
@weizhenzhao @ssbuild  两位大佬，请教您个问题，我现在有汽车领域一万多条的微调多轮对话数据。
微调成功后，在预测对话的时候能  记住 微调数据集中的知识吗？
比如像这个例子（在微调数据集中）：
{"id":5506,"paragraph":[{"q":"06年的乐驰老烧ECM保险丝怎么查","a":["您好，线路有问题，或者ECM内部有问题，","检查一下保险丝到ECM之间的线路，看是否有搭铁的地方。","如果线路正常，更换ECM就好了。"]},{"q":"油泵过热会不会引起这问题。您的回答真给力，特此采纳","a":[]}]}

微调之后，进行对话的时候：
user问：06年的乐驰老烧ECM保险丝怎么查？

机器的回答是否会像这样回答：
机器答复：您好，线路有问题，或者ECM内部有问题，","检查一下保险丝到ECM之间的线路，看是否有搭铁的地方。","如果线路正常，更换ECM就好了

**Comment by HBdingdang** [comment]
@weizhenzhao 您好，请问一下模型训练后有保存训练过程的loss吗，你的loss可视化是自己添加代码展示的吗。我想请教一下训练完成后如何查看训练loss？
