### ISSUE TITLE
infer_finetuning加载权重的问题

### ISSUE THREAD

**Issue by paulcx** [ssbuild/chatglm_finetuning#81]
![20230326092130](https://user-images.githubusercontent.com/738834/227750213-312a8527-d4e3-4577-bfc1-21d35b7762a1.jpg)
加载的时候和训练模型权重不一致，怀疑是不是配置问题？

**Comment by ssbuild** [comment]
model = MyTransformer.load_from_checkpoint(train_weight, config=config,model_args=model_args,
                                                   training_args=training_args,strict=False)

如上修改代码，  try it

**Comment by paulcx** [comment]
可以运行加载，就是回答是空的，不知道什么原因。我再看看
