### ISSUE TITLE
请问：12G显存可以训练模型吗？

### ISSUE THREAD

**Issue by jiaozn** [ssbuild/chatglm_finetuning#82]
项目Readme中看到了下图内容——
请问：我只有3080ti （12G显存），也可以训练模型吗？

![Snipaste_2023-03-26_09-24-04](https://user-images.githubusercontent.com/12379029/227750415-e4d3651f-f711-4756-a613-bc82b66b2179.jpg)

**Comment by ssbuild** [comment]
this just infer model minimum requirements

**Comment by jiaozn** [comment]
> this just infer model minimum requirements

好的……谢谢大佬的秒级回复！
（尽管彻底打破了我的幻想^_^  o(╥﹏╥)o）
