### ISSUE TITLE
预测的速度比训练慢很多正常吗？

### ISSUE THREAD

**Issue by lixiang1991** [ssbuild/chatglm_finetuning#85]
我的显卡是4080，用的lora，16g显存勉强可以支撑batch_size=1的训练，平均每秒8个iter。

预测是用的base_model.chat，预测一次就要3秒多一点。速度差不多比训练要慢30倍。

请问有没有什么提高预测速度的优化方法呀？

**Comment by ssbuild** [comment]
目前的路子就是量化 ， 没太好的方法。
