### ISSUE TITLE
多人同时提问时会挂，请教下如何应付

### ISSUE THREAD

**Issue by jiandam55** [ssbuild/chatglm_finetuning#86]
https://3ad07fc64315a58f89.gradio.live
作者你好，我们发现多人同时提问会socket反应超时，必须重启web_demo.py才行，这个你有何建议不？
比如：加大配置，分布式，还是。。。

**Comment by ssbuild** [comment]
考虑下生成消费者方案

**Comment by jiandam55** [comment]
不能并发，只能排队是吧？我明白了
