### ISSUE TITLE
我权重用空，跑python train.py脚本，报错如下：

### ISSUE THREAD

**Issue by bobo-wmdigit** [ssbuild/chatglm_finetuning#87]
![image](https://user-images.githubusercontent.com/80187914/227837882-6f389a5e-d6ef-4c4e-829a-d61cab3862e3.png)
感觉是token的字典没插进去，但是我没找到位置，有大佬知道吗？

**Comment by ssbuild** [comment]
rm -rf output ， try it

**Comment by bobo-wmdigit** [comment]
Done, running now, thanks for your help.

**Comment by bobo-wmdigit** [comment]
Next question, if I want to add pre-trained weights, what should I do? thanks again :)

**Comment by ssbuild** [comment]
下载权重，在data utils.py配置路径即可。

**Comment by bobo-wmdigit** [comment]
我下了清华的那个，我估计是命名问题，我再来试试
