### ISSUE TITLE
[gMASK]的special token问题

### ISSUE THREAD

**Issue by weizhenzhao** [ssbuild/chatglm_finetuning#88]
https://github.com/ssbuild/chatglm_finetuning/blob/8c0c300108f1310b3c7b12d1ca62c25d541bdd64/data_utils.py#L129

用GHATGLM模型做left_to_right生成式任务，这一行是不是要从encoding空格，变成encoding "[gMASK]"呢？
参考以下链接
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/13706689/227876009-23a90e45-0ee7-421c-8ead-b164bc859e07.png">
https://github.com/THUDM/GLM/blob/4f61ed7237a3b0187f4d62062429348276a78c84/README.md#example5-chinese

**Comment by weizhenzhao** [comment]
啥意思呀？大佬？

**Comment by ssbuild** [comment]
just enhance eos , is not necessary~
