### ISSUE TITLE
当q长度过大训练时爆显存

### ISSUE THREAD

**Issue by jkl375** [ssbuild/chatglm_finetuning#89]
当q长度过长时
max_seq_length设置为2048
train_data_batchsize、val_data_batchsize和test_data_batchsize都设置为1
在8*A100（每块80G）上训练，发现显存不足
![oRI2fif1gK](https://user-images.githubusercontent.com/54523287/227935264-b2876dcc-163e-43bd-84ce-0c77bac4f5f7.jpg)

**Comment by ssbuild** [comment]
smaller max_seq_length
