### ISSUE TITLE
模型训练时能否采用模型并行？

### ISSUE THREAD

**Issue by ScottishFold007** [ssbuild/chatglm_finetuning#9]
现在默认是数据并行的逻辑，但我发现全量参数微调的时候，input长度和target长度拉低也会爆显存，能否采用模型并行的手段来使显存适配模型的大小？

**Comment by ScottishFold007** [comment]
或者使用lora这种技术也是可以的

**Comment by BestSongEver** [comment]
4张V100，batch调整成1，layer是28，还是会爆GPU。有啥办法吗

**Comment by ScottishFold007** [comment]
> 4张V100，batch调整成1，layer是28，还是会爆GPU。有啥办法吗

> 
![Uploading image.png…]()

你是V100多少G的显存，我是8*V100 32G，模型并行刚调通，还是不够，input512 target384

**Comment by BestSongEver** [comment]
> > 4张V100，batch调整成1，layer是28，还是会爆GPU。有啥办法吗
> 
> > 
> ![Uploading image.png…]()
> 
> 你是V100多少G的显存，我是8*V100 32G，模型并行刚调通，还是不够，input512 target384

我是4张32G的卡。这个和input, target关系不大吧。你8张卡感觉应该能跑全量训练，把batch改成1？

**Comment by BestSongEver** [comment]
> > > 4张V100，batch调整成1，layer是28，还是会爆GPU。有啥办法吗
> > 
> > > 
> > ![Uploading image.png…]()
> > 
> > 你是V100多少G的显存，我是8*V100 32G，模型并行刚调通，还是不够，input512 target384
> 
> 我是4张32G的卡。这个和input, target关系不大吧。你8张卡感觉应该能跑全量训练，把batch改成1？
我用200条数据试着微调部分层，但训成了人工智障。

**Comment by ScottishFold007** [comment]
fsdp



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月17日(周五) 下午5:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ssbuild/chatglm_finetuning] 模型训练时能否采用模型并行？ (Issue #9)




  
ScottishFold007
  
你怎么做的模型并行 能介绍一下么 感谢
