### ISSUE TITLE
怎么保存成类似官方模型的形式

### ISSUE THREAD

**Issue by TccccD** [ssbuild/chatglm_finetuning#90]
目前是保存成了ckpt，想问下怎么保存成Transformer的形式

**Comment by ssbuild** [comment]
https://github.com/ssbuild/chatglm_finetuning/blob/d2c0287fd0e6c74fcbb9916b5b13625bf9ff1a55/train.py#L224

**Comment by TccccD** [comment]
> https://github.com/ssbuild/chatglm_finetuning/blob/7435c35af87099a65e40558d5aa3296228446448/train.py#L227
> 
> try it

感谢。训练完成后，我发现eos token id变了：
  "bos_token_id": 150004,
  "eos_token_id": 20002,
原始模型是：
  "bos_token_id": 150004,
  "eos_token_id": 150005,
这应该会影响效果吧？

**Comment by ssbuild** [comment]
good question ，tokenizer eos_token_id is 20002  ， but config eos_token_id  is 15005 , i will make sure later.

**Comment by ssbuild** [comment]
> > https://github.com/ssbuild/chatglm_finetuning/blob/e5cc0fc8e34c1706b243e680c1472da99c3e8b93/train.py#L227
> > 
> > try it
> 
> 这个保存方法应该是lora的？我用的不是lora，是全量参数的finetuning，但没有找到对应的保存方法。

这个方法只支持参数的finetuning ，lora不支持这样保存模型~

**Comment by TccccD** [comment]
> > > https://github.com/ssbuild/chatglm_finetuning/blob/e5cc0fc8e34c1706b243e680c1472da99c3e8b93/train.py#L227
> > > 
> > > try it
> > 
> > 
> > 这个保存方法应该是lora的？我用的不是lora，是全量参数的finetuning，但没有找到对应的保存方法。
> 
> 这个方法只支持全参数的finetuning ，lora不支持这样保存模型~

哦哦，看错了，试了下可以了，感谢~
