### ISSUE TITLE
batch小，优化器用adamw比lion好？

### ISSUE THREAD

**Issue by nieallen** [ssbuild/chatglm_finetuning#92]
好像batch小于64时候，adamw效果比lion好？

**Comment by weizhenzhao** [comment]
@nieallen 
大佬能发下adamw的配置文件吗？
我用adamw 一直没有跑起来。loss一直是nan

**Comment by MichaelToLearn** [comment]
> @nieallen 大佬能发下adamw的配置文件吗？ 我用adamw 一直没有跑起来。loss一直是nan

同
