### ISSUE TITLE
您好，后续可能会添加模型并行的方案吗？

### ISSUE THREAD

**Issue by robin087** [ssbuild/chatglm_finetuning#95]
就是对于16GB V100的显卡来说，跑全参数的训练比较吃力，假如能够在多卡上实施模型并行就能跑更长的数据了，请问有可能会添加模型并行的方案吗？

**Comment by ssbuild** [comment]
ddp or deepspeed is ok

**Comment by robin087** [comment]
就是megatron-lm的那种model parallelism或者deepspeed的pipeline parallelism可能会有吗？

**Comment by ssbuild** [comment]
deepspeed stage 2 3可以并行，更简单。

**Comment by robin087** [comment]
目前我在16GB V100上使用zero3+cpu offload能勉强跑起单轮对话，但是在多轮对话上还是会爆，感觉这个还是有极限的。。。那两个方法感觉能够装载更大的模型，所以想问一下

**Comment by ssbuild** [comment]
可以的，只要硬件足够，就可以驱动更大规模的参数。
