### ISSUE TITLE
执行infer.py(python infer.py)遇到错误：RuntimeError: Library cudart is not initialized，是怎么回事啊？

### ISSUE THREAD

**Issue by xubuvd** [ssbuild/chatglm_finetuning#96]

**Comment by fourseven471** [comment]
> 
减小chat函数最大长度没用哦！ 在model.half().quantize(4).cuda()报错的。
<img width="841" alt="image" src="https://user-images.githubusercontent.com/48342616/228455881-cf5f5797-7bf3-4c2a-93d1-76f4319066fb.png">

**Comment by ssbuild** [comment]
try  torch.cuda.empty_cache()

**Comment by xubuvd** [comment]
如果用的是conda管理环境：
首先用conda list | grep cuda确定该环境cuda运行时版本，如11.7。
然后从nvidia源安装cudatoolkit：conda install cudatoolkit=11.7 -c nvidia

It works!

**Comment by xubuvd** [comment]
> 

这样解决的，建议作者把cudatoolkit放入requirements.txt！

如果用的是conda管理环境：
首先用conda list | grep cuda确定该环境cuda运行时版本，如11.7。
然后从nvidia源安装cudatoolkit：conda install cudatoolkit=11.7 -c nvidia

It works.

**Comment by ssbuild** [comment]
> > 
> 
> 这样解决的，建议作者把cudatoolkit放入requirements.txt！
> 
> 如果用的是conda管理环境： 首先用conda list | grep cuda确定该环境cuda运行时版本，如11.7。 然后从nvidia源安装cudatoolkit：conda install cudatoolkit=11.7 -c nvidia
> 
> It works.

直接放requirements.txt 可能就限制的多，不太自由， 可以建立常见问题md文件 ， 欢迎pr。
