### ISSUE TITLE
你好，如果领域多轮对话数据的话，如何构建多轮qa 数据示例进行微调？

### ISSUE THREAD

**Issue by cristianohello** [ssbuild/chatglm_finetuning#99]
比如：我有个三轮的对话数据，下面这样构建微调数据集合理吗？q：代表用户说的话，a：代表机器说的话。
{"id": 1, "paragraph": [
{"q": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "a": ["用电脑能读数据流吗？水温多少"]}
,{"q": "95", "a": ["继续发动水温就高了？", "上下水管温差怎么样啊？空气是不是都排干净了呢？"]}
,{"q": "是的。上下水管都好的", "a": ["那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！", "您好，先确定一下水循环是否正常，节温器有没有正常打开！如果都是好的，要检查风扇插头有没有电过来，如果有证明风扇是坏的，如果没有在继续查线路吧！"]}]}

**Comment by zhuyanshuo183** [comment]
还是说，把用户说的所有内容组成q，机器回答的组成a？

**Comment by ssbuild** [comment]
> 还是说，把用户说的所有内容组成q，机器回答的组成a？

你这个是标准的结构 ，可以试一下， 建议使用模板结构，参考羊驼模板，自己设计一个。

**Comment by zhuyanshuo183** [comment]
@ssbuild 
是这种格式进行领域微调吗？
{"id": 1, "paragraph": [
{"q": "长城h3风扇不转。继电器好的。保险丝好的传感器新的风扇也新的这是为什么。就是继电器缺一个信号线", "a": ["用电脑能读数据流吗？水温多少"]}, 
{"q": "95", "a": ["继续发动水温就高了？", "上下水管温差怎么样啊？空气是不是都排干净了呢？"]}, 
{"q": "是的。上下水管都好的", "a": ["那就要检查线路了，一般风扇继电器是由电脑控制吸合的，如果电路存在断路，或者电脑坏了的话会出现继电器不吸合的情况！", "您好，先确定一下水循环是否正常，节温器有没有正常打开！如果都是好的，要检查风扇插头有没有电过来，如果有证明风扇是坏的，如果没有在继续查线路吧！"]}]}

**Comment by ssbuild** [comment]
直接这样当然可以学，不过可能会遗忘之前的知识，设计专用模板比较好。

**Comment by zhuyanshuo183** [comment]
@ssbuild 谢谢大佬的建议，我是小白一个。针对我提供的这个case，想要设计专用模板，您能帮我设计一下吗？感谢

**Comment by nieallen** [comment]
> 

同问大佬，我也是多轮数据，可以给一个多轮模板示例吗？

**Comment by nieallen** [comment]
> 直接这样当然可以学，不过可能会遗忘之前的知识，设计专用模板比较好。

但是大佬，单轮数据不也是按max_seq_length长度拼一起送入模型吗？

**Comment by cristianohello** [comment]
能提供一个多轮对话的微调数据组织格式吗？实际业务当中的对话系统，肯定是很多轮次的，不是简单的一问一答形式数据组织格式。就像这种：
    {
        "instruction":"民主评议活动流程",
        "input":"",
        "output":"民主评议活动是指对党员进行定期的民主评议和考核，以促进党员的自我反省和提高，下面是一般的民主评议活动流程：\n-评议前准备工作\n（1）确定评议的时间和地点，并通知参评党员，做好评议材料的准备工作。\n（2）成立民主评议小组，由支部委员会组成，明确评议小组成员名单。\n（3）制定评议方案，明确评议的内容、方法和程序，以及相关的纪律规定。\n-开始评议\n（1）评议小组主持人进行评议活动的介绍，说明评议的目的和意义。\n（2）被评议党员发言，介绍自己的工作情况和思想状况。\n（3）其他党员依次对被评议党员进行评议发言，包括表扬和批评。\n（4）评议小组成员进行综合评价和点评，并对被评议党员提出意见和建议。\n-结束评议\n（1）评议小组主持人对评议活动进行总结，说明下一步工作安排。\n（2）评议小组成员对评议活动的进展和结果进行记录和整理。\n（3）被评议党员根据评议结果进行自我反省和总结，并制定下一步的工作计划。\n以上是一般的民主评议活动流程，需要根据实际情况进行具体的制定和安排。在开展民主评议活动时，应注意尊重被评议党员的权利，遵守评议的程序和规定，确保评议的公正、公开和公正。"
    },
    {
        "instruction":"简述党员的选拔程序",
        "input":"",
        "output":"党员选拔程序一般包括以下几个步骤：\n-推荐：党员候选人需要由推荐人提名。推荐人可以是党组织、党员、群众组织或者个人。一般情况下，推荐人应该了解被推荐人的政治觉悟、工作能力和道德品质等情况。\n-考察：经过推荐后，党组织应该对被推荐人进行考察。这个考察过程一般包括调查、了解、核实和审查等环节，以了解被推荐人的各种情况。\n-确认：经过考察，如果被推荐人符合党员标准，党组织可以决定接受其为预备党员，并进行培养教育。预备党员应该在规定时间内完成预备期，达到预备期考核标准，经过党的支部讨论并经上级党组织批准后，可以成为正式党员。\n-公示：在党员选拔程序中，公示是一个重要环节。党组织应该在一定范围内公示被推荐人的基本情况，接受群众的监督和评议。公示期间，如果有群众对被推荐人有异议，党组织应该及时调查核实。\n-确认：如果经过公示和调查核实，被推荐人仍然符合党员标准，党组织可以决定接受其为党员，并向上级党组织报备。\n需要注意的是，党员选拔程序并非刻板而僵化的程序，党组织应该根据实际情况灵活运用，确保选拔过程公开、公正、公平，并且符合党员标准。"
    }

**Comment by colinpyy** [comment]
> 直接这样当然可以学，不过可能会遗忘之前的知识，设计专用模板比较好。

对于多轮对话本质上其实是把前面的问题与回答加上最后一个问题作为一个问题，最后一个回答作为回答，这样当作一个单论的回复来训练吗？那可不可以把n轮对话拆分成n个单轮的问答每轮问题里包含前面的问答？(q1,a1),(q1+a1+q2,a2),(q1+a1+q2+a2+q3,a3)……这个样子

**Comment by cristianohello** [comment]
@ssbuild 
多轮对话按照(q1,a1),(q1+a1+q2,a2),(q1+a1+q2+a2+q3,a3)……是这样吗？
q和a的不变吗？
{
    "id": 0, "paragraph": [
        #一轮会话
        {
            "q"（还是q1）: "你好，我问一下，从南京到上海的路线是什么？",
            "a": [
                "你好，南京到上海的路线我不知道！"            ]
        },
	{
            "q"（还是q2）: "你好，我问一下，从南京到上海的路线是什么？你好，南京到上海的路线我不知道！那么，上海到北京路线呢？",
            "a": [
                "你好，路线是。。。。。。这样的。"
            ]
        },
        {
            "q"（还是q3）: "你好，我问一下，从南京到上海的路线是什么？你好，南京到上海的路线我不知道！那么，上海到北京路线呢？你好，路线是。。。。。。这样的。好的，谢谢。",
            "a": [
                "不客气"
            ]
        }
    ]
}

还是这样    **(q1,a1),(q2,a2),(q3,a3)**


{
    "id": 0, "paragraph": [
        #一轮会话
        {
            "q": "你好，我问一下，从南京到上海的路线是什么？",
            "a": [
                "你好，南京到上海的路线我不知道！"            ]
        },
		{
            "q": "那么，上海到北京路线呢？",
            "a": [
                "你好，路线是。。。。。。这样的。"
            ]
        },
        {
            "q": "好的，谢谢。",
            "a": [
                "不客气"
            ]
        }
    ]
}

**Comment by ssbuild** [comment]
@cristianohello 
https://github.com/ssbuild/chatglm_finetuning/blob/e98650df476213c00c375c23ce4f2a777bdfc449/data_utils.py#L204

**Comment by cristianohello** [comment]
@ssbuild 

所以不变吗，都是q和a。

**Comment by ssbuild** [comment]
> @ssbuild
> 
> 所以不变吗，都是q和a。

我理解你说这个意思是不是 1个多轮会话 变化多个多轮会话， 如果是这样，从语料上构建多个即可。

**Comment by cristianohello** [comment]
@ssbuild 

不是1个多轮会话 变化多个多轮会话。而是一个多轮对话。

{
"id": 0, "paragraph": [
#一轮会话
{
"q": "你好，我问一下，从南京到上海的路线是什么？",
"a": [
"你好，南京到上海的路线我不知道！" ]
},
{
"q": "那么，上海到北京路线呢？",
"a": [
"你好，路线是。。。。。。这样的。"
]
},
{
"q": "好的，谢谢。",
"a": [
"不客气"
]
}
]
}
这里面的第二组q, a需要变为q2  a2吗，还是说字典的 键 都是q和a。

**Comment by ssbuild** [comment]
抱歉刚才没理解你的意思。
是的， 键值全是q,a

**Comment by cristianohello** [comment]
@ssbuild 好的，谢谢指导。
那么 下面这两种多轮对话数据组织方式，哪种更好呢？
（q1,a1）（q2,a2）（q3,a3）。。。。

（q1,a1）（q1+a1+q2,a2）（q1+a1+q2+a2+q3,a3）。。。。

**Comment by nieallen** [comment]
> @ssbuild 好的，谢谢指导。 那么 下面这两种多轮对话数据组织方式，哪种更好呢？ （q1,a1）（q2,a2）（q3,a3）。。。。
> 
> （q1,a1）（q1+a1+q2,a2）（q1+a1+q2+a2+q3,a3）。。。。

作者已经在data_utils.py的on_get_corpus里做了处理，进入模型的数据就是你第二行的方式

**Comment by cristianohello** [comment]
@nieallen 
那这样的话，我本地进行模型微调的 output.json  这个json的数据组织格式是下面哪种呢？
  
第一种方式如下（（q1,a1）（q1+a1+q2,a2）（q1+a1+q2+a2+q3,a3）。。。。）：
{
"id": 0, "paragraph": [
#一轮会话
{
"q": "你好，我问一下，从南京到上海的路线是什么？",
"a": [
"你好，南京到上海的路线我不知道！" ]
},
{
"q": "你好，我问一下，从南京到上海的路线是什么？你好，南京到上海的路线我不知道！那么，上海到北京路线呢？",
"a": [
"你好，路线是。。。。。。这样的。"
]
},
{
"q": "你好，我问一下，从南京到上海的路线是什么？你好，南京到上海的路线我不知道！那么，上海到北京路线呢？你好，路线是。。。。。。这样的。好的，谢谢。",
"a": [
"不客气"
]
}
]
}


第二种方式如下： (q1,a1),(q2,a2),(q3,a3)

{
"id": 0, "paragraph": [
#一轮会话
{
"q": "你好，我问一下，从南京到上海的路线是什么？",
"a": [
"你好，南京到上海的路线我不知道！" ]
},
{
"q": "那么，上海到北京路线呢？",
"a": [
"你好，路线是。。。。。。这样的。"
]
},
{
"q": "好的，谢谢。",
"a": [
"不客气"
]
}
]
}

**Comment by nieallen** [comment]
> 
是第二种

**Comment by songge25** [comment]
第二种方式如下： (q1,a1),(q2,a2),(q3,a3)

{
"id": 0, "paragraph": [
#一轮会话
{
"q": "你好，我问一下，从南京到上海的路线是什么？",
"a": [
"你好，南京到上海的路线我不知道！" ]
},
{
"q": "那么，上海到北京路线呢？",
"a": [
"你好，路线是。。。。。。这样的。"
]
},
{
"q": "好的，谢谢。",
"a": [
"不客气"
]
}
]
}

**Comment by songge25** [comment]
这种方法 做record的时候报错 
ValueError: Input None is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.
是数据的格式不能这样搞吗

**Comment by ssbuild** [comment]
> "你好，路线是。。。。。。这样的。"
> ]
> },

应该是数据有问题？！，上传下详细的错误信息

**Comment by songge25** [comment]
@ssbuild 数据问题 不好意思，另外想请问下max_length设置是需要在生成record这一步之前设置吗，record生成后，修改无效？

**Comment by ssbuild** [comment]
> @ssbuild 数据问题 不好意思，另外想请问下max_length设置是需要在生成record这一步之前设置吗，record生成后，修改无效？

修改max_length， 需要删除record ， 重新制作数据。

**Comment by songge25** [comment]
@ssbuild 请问下我根据json文件制作record的时候，发现record的进度条显示的数据总数和我json中的数据行数不对应，会多很多，这个是正常的吗？多轮对话数据

**Comment by ssbuild** [comment]
> 

正常，长文本会被拆掉， 也就是record进队条 可能会大于等于 json 样本数量。
